conductor-client/src/main/java/conductor/Conductor.kt
conductor-client/src/main/java/conductor/ConductorTimer.kt
conductor-orchestra-models/src/main/java/conductor/orchestra/Commands.kt
conductor-orchestra/src/main/java/conductor/orchestra/Orchestra.kt
conductor-orchestra/src/main/java/conductor/orchestra/yaml/YamlElementSelector.kt
conductor-orchestra/src/main/java/conductor/orchestra/yaml/YamlFluentCommand.kt
conductor-test/src/main/kotlin/conductor/test/drivers/FakeTimer.kt
conductor-test/src/test/kotlin/conductor/test/IntegrationTest.kt
conductor-test/src/test/resources/019_dont_wait_for_visibility.yaml

Needed in cases where app has a full-screen overlay. Waiting for element to become visible just introduces an unnecessary delay

Add flag to not wait until element is visible

---

maestro-client/src/main/java/maestro/Maestro.kt

Allow Maestro to be started on an existing, persistent GRPC channel

Add Maestro.ios(channel) initializer

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/utils/ViewUtils.kt
recipies/nowinandroid/pick_interests.yaml

Resorting to `waitUntilVisible` as a last measure if the tap did not produce any result

Decreasing wait time in apps that have a screen overlay. Added flow for Now in Android

---

maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt

We were sending key events to iOS without any delay between inputs, possibly causing race conditions and resulting in some events being discarded.

Fix: Added delay between key inputs on iOS

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Address part of issue #107 ([comment](https://github.com/mobile-dev-inc/maestro/issues/107#issuecomment-1235275341))

Fix: wrap Android text in quotes

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt

Fix: Await channel termination when closing a gRPC ManagedChannel

---

maestro-client/src/main/java/maestro/KeyCode.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/034_press_key.yaml

hi all,
I've added AndroidTV Remote navigation to `pressKey()`
- `Remote Dpad Up`
- `Remote Dpad Down`
- `Remote Dpad Left`
- `Remote Dpad Right`
- `Remote Dpad Center`
- `Remote Media Play Pause`
- `Remote Media Stop`
- `Remote Media Next`
- `Remote Media Previous`
- `Remote Media Rewind`
- `Remote Media Fast Forward`
please let me know if I miss anything 🙇🏻

feature: AndroidTV-Remote navigation

---

maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-orchestra-models/build.gradle
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra-models/src/test/kotlin/LitmusTest.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandTest.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

This is the same set of changes from https://github.com/mobile-dev-inc/maestro/pull/150 but with added tests for `MaestroCommand` serialisation for the backend.
**Things to note**
1. The `MaestroCommandSerializer` has two exceptions with property names `tapOnPoint` and `tapOnPoint`. The rest of the commands have a `Command` suffix (e.g. `swipeCommand`). We preserve this behavior so that the contract with the backend remains the same after the refactor.
2. The `MaestroCommandSerializationTest` has duplication. I found IntelliJ's syntax highlighting from language injection (`@Language("json")`) useful in the IDE. We could go with a JUnit parameterised test or a combination approval test if you find it too verbose.
3. I have added a comment to `MaestroCommand` on why we need the custom …

Prepare maestro to make it easier to add new commands

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/device/AccessibilityNode.kt

Text fields have their value (and Hint) reported as `AXValue` field that we were not taking into account.

Fix: populate iOS accessibility value

---

maestro-cli/src/main/java/maestro/cli/command/QueryCommand.kt
maestro-client/src/main/java/maestro/Filters.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/038_partial_id.yaml

There seem to be some confusion about how to match views by ID on Android: #163 
Tweaking the logic to match by ID following this order:
- First, try to find any view with id that matches a regex
- If there is none, find a view where id without package name matches a regex

Tweak: allowing to skip package name when matching by id

---

maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt

It appears that there are still some race conditions: #167 
Introducing 25ms did help greatly last time, tripling the latency just to be on a safe side

Tweak: increase iOS input latency

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/038_hide_keyboard.yaml
maestro-test/src/test/resources/039_hide_keyboard.yaml

hi @dmitry-zaitsev 
I have an issue when try to `tapOn` a button that blocked by device keyboard.
- the UI before keyboard is showing
- the UI after keyboard is showing
I've tried to add `hideKeyboard()` event to avoid that failed case (before `tapOn()` desired button)

feat: add hideKeyboard event

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Fix: Making sure gRPC channel is functional before considering AndroidDriver operational

---

maestro-client/build.gradle
maestro-client/src/main/java/maestro/Maestro.kt
maestro-test/build.gradle
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeLayoutElement.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

One of the common sources of confusion when using Maestro is - why sometimes we tap on a view multiple times?
This PR helps to mitigate that by _also_ comparing screenshots before and after user interaction to verify that indeed something have visibly changed in the hierarchy.
To facilitate the testing, `FakeDriver` was updated to actually draw a screen onto an image, just like a real device would.

Tweak: Comparing screenshots after tapping on a view

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

- Using `idb.describePoint` to find children of a tab bar view
- Improving efficiency of Maestro by removing redundant `viewHierarchy()` calls and reducing number of tap probes from 3 to 2

Tweak: scanning contents of iOS group views to try and find more children

---

maestro-client/build.gradle
maestro-client/src/main/java/maestro/android/AndroidAppFiles.kt
maestro-client/src/main/java/maestro/android/AndroidExt.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Fixes: https://github.com/mobile-dev-inc/maestro/issues/172
1. Implementing leakcanary
2. Write down the following test:
```
val dadb =  Dadb.create("localhost", 5555)
val maestro = Maestro.android(dadb)
repeat(10) {
maestro.launchApp("com.example.name")
Thread.sleep(3000)
}
```
Was able to observe that out of 10 majority times leak canary launcher opens
Check for launcher activities and opens the one which starts with the app id passed. Since all the third-party ones will start with different package id.

Opens only app based launcher activity in case of 3rd party launcher

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

This reverts commit 56682cb22e8b31853b64b1a863a0753dba5f74ca.
Reverting commit because it results in timeout exceptions on starting maestro.
N/A
TimeoutExceptions on multiple production analyses

Revert "Fix: Making sure gRPC channel is functional before considering AndroidDriver operational"

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Tested on an emulator
`hideKeyboard` was not always working
Fixes #229

Fix: hide keyboard on Android

---

maestro-client/src/main/java/maestro/Filters.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/048_tapOn_clickable.yaml

When selecting an element among multiple matching candidates, prioritise ones that have `clickable=true`. Note that we keep the default behaviour in cases where `index` is specified explicitly
Added integration test
Fixes #228

Tweak: prioritise cliackable elements

---

maestro-cli/build.gradle
maestro-cli/src/main/java/maestro/cli/util/MaestroFactory.kt
maestro-client/build.gradle

Maestro now supports any Android device that is supported by a local adb server. This includes USB devices!
Tested that Android Emulator and Physical device interaction works as expected.
#80

Enable USB support for Android

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/050_clipboard_paste.yaml

add `paste from clipboard` event/action.
https://user-images.githubusercontent.com/6134774/193421338-1d3997bf-fc91-45bc-9e46-2dcff6d4318f.mov
https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1664560340755779

feat: paste from clipboard

---

maestro
maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt

As the mobile.dev backend has been updated to not require an upload name, this change aligns maestro-cli with this change and makes the upload name an optional parameter instead of a positional argument.
**Usage**
Before
`maestro upload TestUpload <appFile> <flowFile>`
After
`maestro upload --name TestUpload <appFile> <flowFile>`

breaking change: change upload name to be an option instead of positional argument

---

maestro-client/src/main/java/maestro/Filters.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/055_compare_regex.yaml

When an element selector contains regex special characters we can easily miss the view, for example:
```
- tapOn: (Hello World)
```
Will not find a view with text `(Hello World)` as parentheses considered to be a part of the regex and are ignored. This fix changes that by also trying to match regex pattern itself against the text
- Integration test
Fixes #242

Fix: also compare regex as text when searching for view

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-client/src/main/java/maestro/Filters.kt
maestro-client/src/main/java/maestro/TreeNode.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/device/AccessibilityNode.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/ElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeLayoutElement.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/054_enabled.yaml

- Introduce `enabled` property into `ElementSelector`
- Introduce `focused`, `selected`, `checked` property in `TreeNode` for better layout change detection (but without introducing them in `ElementSelector` as they are Android-only)
- Tested locally on Android and iOS
- Integration tests
Fixes #249

Feature: enabled property + extra comparison properties

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/LoginCommand.kt

Fixing the following error:
```
maestro login
No auth token found
Sign In or Sign Up using your company email address:
> leland@mobile.dev
We sent a login link to leland@mobile.dev. Click on the link there to finish logging in...
java.lang.IllegalStateException: closed
at okio.RealBufferedSource.select(RealBufferedSource.kt:218)
at okhttp3.internal.Util.readBomAsCharset(Util.kt:265)
at okhttp3.ResponseBody.string(ResponseBody.kt:187)
at maestro.cli.auth.Auth.triggerSignInFlow(Auth.kt:79)
at maestro.cli.command.LoginCommand.call(LoginCommand.kt:29)
at maestro.cli.command.LoginCommand.call(LoginCommand.kt:9)
at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
at picocli.CommandLine.access$1200(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandW …
```

Fix the login command

---

RELEASING.md

Simplifying `RELEASING.md` as it contained quite a lot of scripts that do not do much while still require manual intervention

Simplify RELEASING.md

---

maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlRunFlow.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/057_runFlow_env.yaml
maestro-test/src/test/resources/057_subflow.yaml
maestro-test/src/test/resources/057_subflow_override.yaml

Passing variables down to `runFlow` command:
```
- runFlow:
file: subFlow.yaml
env:
SUB_PARAMETER: Hello World
```
Sub flows within a `runFlow` can override parameters with their own values, just like you would expect in any programming language.
Integration tests.

Feature: added env parameter to runFlow

---

maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/058_inline_env.yaml
maestro-test/src/test/resources/058_subflow.yaml

Allowing to inline `env` parameters directly in file at the top level.
Why at the top level - since env variables are resolved statically at parsing time, we are not going to be able to handle cases where a user provides multiple `env` commands in a row. Hence limiting it to a top-level field for now.
Integration test.

Feature: Inline env

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Condition.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/049_run_flow_conditionally.yaml

We were not taking `env` parameters into account in conditions
Fixes #328

Fix: inject env parameters into conditions

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-client/src/main/java/maestro/MaestroTimer.kt

Check if
* idb port is open
* sim boot status is booted
* accessibility info returns frames with non-zero width
Manual testing
When running `maestro test` on an iOS Simulator, the error `java.lang.IllegalStateException: idb_companion did not start in time` can mean several things:
* idb did not start correctly
* iOS Simulator boot time too long
* Issue with Accessibility frameworks SDK / Simulator runtime
This change checks for these causes and reports with a different error message for each of them.

Better check ios simulator status when starting tests

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

* Timeout idb_companion starting if socket is not open within one minute
* Timeout Simulator booting if bootstatus is not positive within two minutes
* Print the to the cli what is being waited on
Tested locally
Launching idb_companion can take up to a minute, Below a minute makes maestro runs unstable (sometimes idb is fast enough, sometimes it isn't).
Booting the simulator on an older, less capable Mac for the first time will take over a minute to complete.
Users waiting for maestro to start idb and the simulator are informed via cli messages.

Wait longer for idb and simulator, print wait status to cli

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/SwipeDirection.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSwipe.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/017_swipe.yaml
maestro-test/src/test/resources/059_directional_swipe_command.yaml

Adds directional swipe: RIGHT, LEFT, DOWN, UP. This will help in use cases like swiping pagers in onboarding irrespective of device width height. API:
```
- swipe:
direction: LEFT | RIGHT | UP | DOWN
```
PS: start and end coordinates still remain but are optional now.
Swipe speed can be controlled by supplying duration. More the duration slower the swipe speed. The lesser the duration the more swipe speed. API:
```
- swipe:
direction: LEFT
duration: 300
```
Accounting scroll delta and duration which fixes iOS vertical scrolling as well
https://user-images.githubusercontent.com/12881364/200290424-32c19707-3bbf-4eef-8658-7dfd175e947a.mp4
https://user-images.githubusercontent.com/12881364/200289793-119f3a61-56f5-4d06-b8d5-ab98b445bbb9.mp4 …

Adds directional swipe, makes swipe speed configurable through duration and fix iOS scroll

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-client/src/main/java/maestro/MaestroTimer.kt

Currently idb_companion start often hangs infinitely with the message `Waiting for idb service to start...`, this PR fixes that.
Tested locally

Fix idb service start hanging issue

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

Several different improvements that should help speed up Maestro flows:
- In case if there is no change after a tap on element we retry only once instead of twice
- `waitUntilVisible` now default to `false` as this is a rather exotic use case that is unlikely to be needed by majority of apps
- Starting timeout countdown from the latest iteraction/mutation of view hierarchy instead of current time. This makes consequent Optional steps as well as Assertions _much_ faster as they can just assume that hierarchy did not change and are going to fail fast
- `eraseText` no longer waits for app to settle on _each_ key press
- Caching `deviceInfo` value, allowing it to be reused across commands (saves a network call on each command)

Tweaks: speeding up Maestro flows

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Fix launching app when resolving launcher activity from manifest is throwing NullPointerException

Fixing launching app when launcher activity throws `NullPointerException`

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

Do not kill idb_companion when running maestro. Maestro should not kill an unrelated process.
Instead, warn the user that idb_companion is running and exit.
Tested locally
MOB-1551

Do not kill idb_companion, exit with an error instead

---

maestro-cli/build.gradle

Configures jreleaser Gradle plugin in a way that `openjdk@8` will not be added as a dependency in the [generated brew formula ](https://github.com/mobile-dev-inc/homebrew-tap/blob/8ab370773f5b2a2dbf1eb57a0533e0dc317c31fb/Formula/maestro.rb#L10)
- Pull these changes locally
- Generate the target formula
```bash
$> ./gradlew clean maestro-cli:jreleaserPackage
```
- Check no `openjdk` dependency in the generated formula
```bash
$> grep -L openjdk maestro-cli/build/jreleaser/package/maestro/brew/Formula/maestro.rb
```
Fixes #402 
An update in public docs warning users that a proper JDK available at `$PATH` is required in order to run **maestro** is probably useful as well.  🙂

Opt-out from jdk8 dependency when installing with brew

---

maestro-cli/build.gradle
maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/debuglog/DebugLogStore.kt
maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

- DebugLogStore stores log files in $HOME/Library/Logs/maestro/ (similar but different dirs for Linux and Windows).
- Add method to DebugLogStore to capture all output of a subprocess
- DebugLogStore deletes any logs except the last 5 (this run included)
- Store idb_companion logs using DebugLogStore
Tested locally

Store idb_companion logs for later inspection

---

maestro-cli/build.gradle
maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/model/TestExecutionSummary.kt
maestro-cli/src/main/java/maestro/cli/report/JUnitTestSuiteReporter.kt
maestro-cli/src/main/java/maestro/cli/report/ReportFormat.kt
maestro-cli/src/main/java/maestro/cli/report/ReporterFactory.kt
maestro-cli/src/main/java/maestro/cli/report/TestSuiteReporter.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-cli/src/test/kotlin/maestro/cli/report/JUnitTestSuiteReporterTest.kt

Adding `--report` option to a `test` command that generates a JUnit-compatible test report in XML format. Sample output:
```
<?xml version='1.0' encoding='UTF-8'?>
<testsuites>
<testsuite name="Test Suite" device="Pixel_3_API_30_Google_Play_" tests="6" failures="2">
<testcase id="misconfigured" name="misconfigured">
<failure>Could not parse Flow file:
Flow files must contain a config section and a commands section. Found 1 section: ../DevToolTester/android/.mobiledev/misconfigured.yaml</failure>
</testcase>
<testcase id="failing" name="Failing test">
<failure>Element not found: Text matching regex: Something incorrect</failure>
</testcase>
<testcase id="appCrash" name="App Crash"/>
<testcase id="memoryLeak" name="Memory Leak"/>
<testcase id="loggedOutContent" name="Logged Out Content"/> …
```

Feature: test reports

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/050_clipboard_paste.yaml

- Removes clipboardPaste command
Reason: Does not work as intended. Substitute command copytextFrom/pasteText will be introduced to facilitate copy/paste

removes clipboardPaste command

---

maestro-cli/src/main/java/maestro/cli/debuglog/DebugLogStore.kt
maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

Use `logger.warning()` to message both to the console as well as to the debug log.
If this is accepted I'll update all the println() lines to use `logger.warning()` instead.
`logger.severe()` will print "Error: <message>" to the console.

Use logger.warning to send a message to the console

---

maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt

`./gradlew build` fails due to a duplicate label in YamlFluentCommand.kt

Remove duplicate label "inputRandomText"

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt

Adds `android-api-level` flag to the CLI (in both `cloud` and `upload` commands) so the user can select which of the supported API levels they can run the Flow against. The error handling (what API versions are supported will be handled by the server).

Adding androidApiLevel to maestro CLI

---

maestro-client/build.gradle
maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-client/src/main/java/maestro/js/JsHttp.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/build.gradle
maestro-test/src/test/kotlin/maestro/test/JsEngineTest.kt

Introducing an HTTP API for Javascript:
Sample usage:
```
var response = http.get('http://example.com')
json(response.body).myField
```
Extended usage:
```
var response = http.post('http://example.com', {
headers: {
Authorization: 'Bearer Token'
},
body: JSON.stringify({
payload: 'Some value'
})
})
if (response.ok) {
output.myAction = json(response.data).someField
} else {
throw "Failed to obtain response"
}
```
- Introduced new `JsEngineTest` that test Javascript functionality in isolation
- Using Wiremock to test HTTP interations

Feature: make HTTP requests from Javascript

---

maestro-client/src/main/java/maestro/android/AndroidAppFiles.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Samsung devices have a protected `user 150` which is basically a Samsung Secure Folder. Shell refuses to execute `pm list packages`
Use a `--user 0` argument in both places in the code. This specifies usage only within system user, but not any others.
Tried this command on my device locally
#418

Fix running on Samsung devices 

---

maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/066_copyText_jsVar.yaml

Store output of `copyTextFrom` command in `maestro.copiedText` JS variable

Feature: store copied text in a JS variable

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/067_assertTrue_fail.yaml
maestro-test/src/test/resources/067_assertTrue_pass.yaml

- `assertTrue` command that verifies that input is JS-truthy
- Internal refactoring - deprecated `AssertCommand` in favour of `AssertConditionCommand` so that we can encapsulate logic inside of `Condition` object and avoid duplication
Example:
```
- assertTrue: ${1 + 1}    # passes
- assertTrue: ${1 - 1}    # fails, since 0 is treated as False
```

Feature: assertTrue

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt

When running a single test with `--format`, produce the same output as if running a directory

Tweak: report generation for single test runs

---

maestro-client/src/main/java/maestro/Errors.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlWaitForAnimationToEndCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/069_wait_for_animation_to_end.yaml

Implement a command to wait until an animation has fully finished.
Some suitable use-cases: splash screen animation, animation is triggered as a side-effect of some action (i.e. scroll or swipe)
yaml example:
```
appId: org.wikimedia.wikipedia
---
- launchApp
- waitForAnimationToEnd
```
Tested locally with apps that have splash screen animations

Feature: Wait for animation end command

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/070_evalScript.yaml

`evalScript` is a convenience command for evaluating one-liner snippets of JS code. That comes in particularly handy when working with `copyTextFrom` command:
```
- copyTextFrom:
id: "myField"
- evalScript: ${output.result = 'Hello ' + maestro.copiedText}
- inputText: ${output.result}
```

Feature: evalScript

---

maestro-android/src/androidTest/java/dev/mobile/maestro/MaestroDriverService.kt

Letter 'z' is actually 122 in ASCII table and 54 in android keycode, so being out of range is probably the issue here.
Fix for letter 'z' being omitted during input

Fix for letter 'z' being omitted during input

---

maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt

Needed to increase the delay between stopApp and clearState, since flows were flaky with 500ms value
Tested on local machine MacBook Pro (16-inch, 2019) 2,4 GHz 8-Core Intel Core i9, when setting a delay to ~800ms flakiness started to drop, at a value of 900ms 100% of the flows succeeded, decided to set it to 1500ms to be on a safe side with slower machines

Fix clearState issue on iOS

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

About 2x speed up of Maestro:
- Fixed bug in `waitForAppToSettle` that was always doing 10 iterations
- Removed redundant describePoint calls from iOS Driver (soon to be replaced with XCUITest driver anyway)
- Removed redundant calls to `viewHierarchy()`

Tweak: speed up Maestro

---

maestro-cli/src/main/java/maestro/cli/view/ErrorViewUtils.kt
maestro-orchestra/src/main/java/maestro/orchestra/error/InvalidFlowFile.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt

Introduces new exception `InvalidFlowFile` for invalid flow files. Previously we were using `InvalidInitFlowFile`
No need.
Incorrect error message for invalid flows

Replaces initFlowFile exception

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

When testing our internal infra, it would be very convenient to let `maestro cloud` fail on `CANCELED` status ensure that the whole stack behaves correctly E2E.

Tweak: internal flag to fail on cancellations

---

scripts/install.sh

Once deployed to GCP, user would be able to run scripts like that to install a specific version:
```
export MAESTRO_VERSION=1.16.0
curl -Ls "https://get.maestro.mobile.dev" | bash
```
or one-liner
```
export MAESTRO_VERSION=1.16.0; curl -Ls "https://get.maestro.mobile.dev" | bash
```

Feature: allow to install a specific Maestro version

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

No longer depend on PATH being set in any sort of way. Only rely on ANDROID_HOME environment variable variants to exist.

Fix emulator binary discovery

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt

Change the warning on `maestro hierarchy` from a deprecation notice to "Have you tried Studio?"

Un-deprecate the hierarchy command, inform about Studio

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/util/WorkspaceUtils.kt
maestro-cli/src/test/kotlin/maestro/cli/util/WorkspaceUtilsTest.kt
maestro-cli/src/test/resources/tags/flowA.yaml
maestro-cli/src/test/resources/tags/flowB.yaml
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroConfig.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt

This PR adds the `--include-tags` and `--exclude-tags` parameters for the `cloud` command [1]. With these options, the users are able to filter the Flows containing (or not) those tags.
Usage example:
The `--include-tags` should look for all flows that contain the provided tag and it doesn't matter if those Flows also contain other tags. On the other hand, the `--exclude-tags` would remove from the list of Flows to run any Flow that contains the provided tags.
Let's say a user has two flows:
```
tags: dev,pull-request
```
```
tags: dev
```
In the scenario above:
- If they use `--include-tags=dev` we would run flowA and flowB. 
- If they use `--exclude-tags=pull-request` we would run only flowB.
- If they use `--exclude-tags=dev` we wouldn't …

Add capacity of filtering flows based on the --include-tags and --exclude-tags for maestro cloud command

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt

For the full explanation of how the feature works, please see PR #545

Add capacity of filtering flows based on the --include-tags and --exclude-tags for maestro test command

---

maestro-xcuitest-driver/src/main/kotlin/util/CommandLineUtils.kt

Deprecate the runCommand() that slits up the single string argument. Refer to the runCommand() accepts a list of arguments.

Deprecate string splitting runCommand

---

maestro-client/src/main/java/maestro/Filters.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/073_handle_linebreaks.yaml

From user's perspective, linebreak might be interpreted as a whitespace when rendered on the screen. To reduce mental load on test's author, we are going to optionally treat linebreaks as a whitespace.

Tweak: handle linebreaks

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt

Fix: do not fail studio command if Desktop.browse doesn't work

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/SwipeDirection.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSwipe.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/074_directional_swipe_element.yaml

1. Changing start and end points for directional swipe: LEFT, RIGHT, UP, DOWN
2. Changed default duration to swipe to 400 ms
3. Now it's going to be possible to directionally swipe on the element:
```
- swipe:
direction: RIGHT
element: 
id: "@id/some_list_view"
```
https://user-images.githubusercontent.com/12881364/211632725-62aadc6c-e227-46fb-8aae-068c65bbd745.mp4
https://user-images.githubusercontent.com/12881364/211633875-00acdf40-653a-44d3-8472-7d28e1aebb12.mp4
https://user-images.githubusercontent.com/12881364/211651142-a82d2e6a-efa9-434a-b42e-c3f0a1188c62.mp4
https://user-images.githubusercontent.com/12881364/211653184-1b23de8d-76e8-4162-aee6-b40dda9f1d14.mp4
https://user-images.githubusercontent.com/12881364/211654038-44418f2a-cc87-49e3-8d08-e28c83a85fc9.mp4 …

Scroll swipe improvements

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/BugReportCommand.kt
maestro-cli/src/main/java/maestro/cli/update/Updates.kt
maestro-cli/src/main/java/maestro/cli/util/ErrorReporter.kt

- Add an error report mechanism: Every time an exception is detected by `picocli` it will send the exception details + the command executed to `api.mobile.dev`. 
- This mechanism tries to not collect any PII information.
- `-e/--env` can have PII information, so this PR also hash the values with SHA-256.
- Also, there is a timeout of 1 second to complete the request to make sure that the user experience is not affected.
- Add `SystemInformationInterceptor` to `ApiClient` to simplify adding system information for each request.
Tested manually:
- Modified an existing maestro command to always throw a CLIError
- Verified if the request went through
- Send a _category_ of error. This could be made easier if there are custom exceptions for each _category_.
- Prompt the user to send all logs …

Feat: add error report mechanism

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

This PR fixes an issue with opening links that contain extras (example://deeplink?a=100&b=200)
Solution originated from [here](https://stackoverflow.com/questions/28802115/i-am-trying-to-test-android-deep-link-urls-through-adb-to-launch-my-app#comment118439409_58742435)
Before:
After:

Fix openLink command to support extras

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Starting point needs to be slightly lower on iOS, because of [safe areas](https://developer.apple.com/design/human-interface-guidelines/foundations/layout/).
tested on iPhoneSE (no-notch device) and iPhone14 simulators
```
- swipe:
direction: DOWN
```
was opening notifications screen all the time

fix starting point for iOS swipe command

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Condition.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlExtendedWaitUntil.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/resources/042_extended_wait.yaml

- Updates `extendedWaitUntil` to use AssertConditionCommand
- Updates `extendedWaitUntil` timeout to be parsed as a `String` in order to allow ENV variables & JS
- Updated integration test
- Manual test
- extendedWaitUntil timeout was not able to parse ENV variables

Allows extendedWaitUntil to use ENV variables in timeout

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/model/TestExecutionSummary.kt
maestro-cli/src/main/java/maestro/cli/report/JUnitTestSuiteReporter.kt

Same `--format` flag and same output format as with `maestro test`. The only caveat is that we do not actually print out why test failed exactly as we do not have an error message (yet)

Feature: generating test report for maestro cloud

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

The last dependency that relies on a local device

Tweak: Remove XCTestIOSDevice dependency on xcrun

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/update/Updates.kt
maestro-cli/src/main/java/maestro/cli/util/CiUtils.kt

Set device uuid according to the following logic
- If `MDEV_CI` is set, use whatever value is provided
- Check for known CI env vars and try to infer the right CI provider
- Fallback to check if `CI` is set to at least know we are in a CI environment

Use CI provider as device UUID when available

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt

JS scripts are not evaluated with the selector of the swipe command, leading to situations where users are not able to use the js output in the swipe command.
JS file:
```
output.home = {
languageList: 'org.wikipedia:id/option_label',
languageText: "1.		English"
}
```
Flow:
```
appId: com.example 
---
- runScript: output.js
- swipe:
from: 
id: ${output.home.languageList}
text: ${output.home.languageText}
direction: LEFT
```
#Fix
https://user-images.githubusercontent.com/12881364/213127460-3edda2b9-c434-4e4d-8d49-6d6e5fa603f0.mp4

Evaluate JS scripts with element selector in SwipeCommand

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-cli/src/main/java/maestro/cli/device/PickDeviceInteractor.kt

`prepareDevice` also needs to be called when deviceId is present
Tested:
- `maestro test` with --device provided
- `maestro test` with --udid provided
- `maestro test` without arguments
https://github.com/mobile-dev-inc/maestro/issues/509

Maestro fails to launch on iOS if --device parameter is present

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Bug:
With the following command:
```
- swipe:
from: 
text: "Collections.*"
direction: LEFT 
```
From the above, the list is expected to swipe but rather the command does scroll. 
https://user-images.githubusercontent.com/12881364/213436789-59e75ab7-d96e-4d3e-bc5a-5be9529b9a83.mov
We should pivot the x and y coordinates looking at the direction:
- LEFT, RIGHT should stay pivoted around the element Y coordinate
- UP, DOWN should stay pivoted around the element X coordinate
https://user-images.githubusercontent.com/12881364/213437310-a21b3028-bca6-4964-91e1-9247047aa43b.mov

Change the end coordinates for swipe element

---

maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt

Use `shutdownNow` now instead of `shutdown` to close the grpc channel.
From documentation:
Initiates a forceful shutdown in which preexisting and new calls are cancelled. Although forceful, the shutdown process is still not instantaneous; {@link #isTerminated()} will likely return {@code false} immediately after this method returns.
Tested:
https://github.com/mobile-dev-inc/maestro/issues/624

idb_companion fails to start due to gRPC timeout exception

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSwipe.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/078_swipe_relative.yaml

Support percentage-based start and end coordinates that could help to be dimension agnostic and prevent giving absolute value.
Sample:
```
- swipe:
start: 10%,50%
end: 90%,50% 
```
https://user-images.githubusercontent.com/12881364/213431391-f2f6ea5c-a095-426f-b52c-61a05f2c95be.mov
https://user-images.githubusercontent.com/12881364/213431409-c6989a8f-2d86-4764-a7ce-463fa262d466.mov

Relatively swipe with percentage based start and end coordinates

---

maestro-client/src/main/java/maestro/ScrollDirection.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlScrollUntilVisible.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/079_scroll_until_visible.yaml

Adds new command to scroll until an element is visible.
Example
```yaml
- scrollUntilVisible:
element:
text: "MyElementText"
direction: DOWN
timeout: 50000
```
- Manual testing with Wikipedia app (Android/iOS)
- Integration test

Feature scroll until view is visible

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-cli/src/main/java/maestro/cli/device/Platform.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-client/build.gradle
maestro-client/src/main/java/maestro/KeyCode.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/Platform.kt
maestro-client/src/main/java/maestro/drivers/WebDriver.kt
maestro-client/src/main/resources/maestro-web.js
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt

Adds a `WebDriver` that allows running Maestro Flows against a web device (powered by Selenium + Chromium). 
Launch Maestro Studio and select the available web device and the Maestro documentation page will be opened and in which you can see all available elements, their selectors and so on.
Simply enter a URL (including protocol) as the `appId` and the website will be loaded as part of the `launchApp` command.
Example flow:
```yaml
appId: https://maestro.mobile.dev
---
- launchApp
- tapOn:
id: "Search…"
index: 1
- tapOn: "Search content…"
- inputText: "Writing Your First Flow"
- tapOn:
text: "Getting Started"
index: 2
- assertVisible:
text: "Writing Your First Flow"
index: 1
```

[experimental] Implement WebDriver

---

maestro-client/src/main/java/maestro/Filters.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/ElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlElementSelector.kt
maestro-test/src/test/resources/032_element_index.yaml

Additionally, fixed a small issue that prevented usage of `index` without any other selector

Tweak: allow JS injection for index selector

---

maestro-cli/src/main/java/maestro/cli/db/KeyValueStore.kt

Maestro closes the driver even when another session is ongoing. Get the current version of db before committing to DB and querying

Get the current state of db before query/update

---

maestro-client/src/main/java/maestro/FindElementResult.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

`findElement` already fetches hierarchy tree that can be reused in subsequent `waitForAppToSettle` operation 
tested with Wikipedia and food truck apps
verified that it saves 500-700ms per tapOn command

Remove excessive hierarchy request for tapOn command

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/UiElement.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/079_scroll_until_visible.yaml

Improves ScrollUntilVisible & fixes issues with iOS / Webviews
- iOS Safari: www.duckduckgo.com
- iOS Maps
- **Fix**: ScrollUntilVisible now checks if an element is visible within viewport bounds.
- **Tweak**: Scrolling will now start from the center of the screen. Avoids side effects like dragging bottom drawers.
- **Tweak**: Better element alignment towards the center i.e it will scroll a bit more if the element is barely visible at a corner.

Updates scroll until visible to work within viewport bounds

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/UiElement.kt
maestro-client/src/main/java/maestro/ViewHierarchy.kt
maestro-client/src/test/java/maestro/UiElementTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/080_hierarchy_pruning_assert_visible.yaml
maestro-test/src/test/resources/081_hierarchy_pruning_assert_not_visible.yaml

Currently view hierarchy might return out of bound elements. This change will filter elements out of screen bounds.
iOS Webview pages
`assertVisible`

Removes out of bound hierarchy elements

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlScrollUntilVisible.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/079_scroll_until_visible.yaml

- Adds command configuration for scroll speed.
- Adds command configuration for element visibility on screen before assertion becomes true. (Helpful to scroll until element becomes fully visible)
Manual & Existing integration tests
FIx: Element detection didn't always work as intended

Adds speed and visibility percentage to scroll until visible

---

maestro-studio/web/src/Examples.tsx

To reduce cognitive load while writing test. Match texts with \n as well.
For the following screen:
Maestro studio inspects an invalid command right now:
```
- tapOn: "LOGIN IS THIS 
WITH NEW LINE"
```
With the change now we can match this text with the following:
```
- tapOn: "LOGIN IS THIS WITH NEW LINE"
```

[MOB 1893] Handle line breaks in studio and matching

---

maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerCommand.kt
maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerSetupCommand.kt
maestro-studio/server/src/main/java/maestro/studio/MockInteractor.kt

Adds a new `maestro mockserver setup` command that prints out the project id that is needed to initialize the Maestro SDK when wanting to integrate with mock server. If the user is not logged in an error message is displayed that prompts them to run `maestro login` and then try again.
```
➜  maestro git:(MOB-1902) ✗ ./maestro mockserver setup
Project id: 37e06c0c-8300-4c46-a81a-2352ca5ff57d
Run maestro mockserver open to get started with Maestro Mock Server!
```

Add maestro mockserver setup command

---

maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerCommand.kt
maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerInitCommand.kt
maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerOpenCommand.kt
maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerProjectIdCommand.kt
maestro-studio/server/src/main/java/maestro/studio/MaestroStudio.kt
maestro-studio/server/src/main/java/maestro/studio/MockService.kt
maestro-studio/web/src/MockServerInstructions.tsx

- Don't require a running simulator/emulator when launching mockserver
- Rename `mockserver scaffold` and `mockserver setup` commands to be more descriptive

Minor fixes to Mock server

---

maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerOpenCommand.kt
maestro-studio/server/src/main/java/maestro/studio/MockInteractor.kt
maestro-studio/web/src/MockPage.tsx
maestro-studio/web/src/MockServerInstructions.tsx
maestro-studio/web/src/api.ts

- Fix a bug causing mock server UI to exit right after opening instead of waiting on Ctrl  + C
- Fix syntax error in welcome instructions

Fix maestro mockserver open command exiting

---

maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt

After removing the app's data folder, create all directories that are supplied by the OS by default.
Ran flows on various customer apps that used to crash with clearState
https://github.com/mobile-dev-inc/maestro/issues/732

Resolve crashes after clearState due to missing system directories

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

It appears that adb responds way too quickly when accepting input, resulting in next commands being executed prematurely. Adding artificial delay to counter that.

Fix: add delay after key press on Android

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/053_repeat_times.yaml

Rhino JS returns values as Double instead of Int, so we need to do conversion String->Double->Int instead of String->Int

Fix: repeat.times was not working with JS input

---

maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerDeployCommand.kt

Make `workspace` an optional argument and fallback to `./maestro/mockserver` when not specified. If that directory exists, use that when deploying the rules. It is still possible to specify the directory of rules by running `maestro mockserver deploy <directory>` so this is just for convenience.
Tested locally.

Add default workspace directory to mockserver deploy command

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Tested using patch in Wikipedia app:
```
func readKeychain() -> Bool {
let query = [
kSecClass: kSecClassGenericPassword,
kSecReturnData: true
] as CFDictionary
var result: AnyObject?
SecItemCopyMatching(query, &result)
return (result as? Data)?.isEmpty == false
}
func setKeychain() {
let query = [
kSecValueData: "data".data(using: .utf8)!,
kSecClass: kSecClassGenericPassword
] as CFDictionary
let status = SecItemAdd(query, nil)
if status != errSecSuccess {
print("Keychain error: \(status)")
}
}
private func updateUIStrings() {
let text = readKeychain() ? "Keychain set" : "Keychain cleared"
setKeychain()
```
* launch app: Keychain cleared
* kill and relaunch app: Keychain set
* Run flow with launchApp with clearKeychain: Keychain cleared

Use xcrun for clearKeychain

---

maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-xcuitest-driver/src/main/kotlin/util/CommandLineUtils.kt
maestro-xcuitest-driver/src/main/kotlin/util/XCRunnerSimctl.kt

Refactor all subprocess calls which use string interpolation to pass separate arguments instead.

Refactor unsafe subprocess calls to safer ones

---

maestro-client/src/main/resources/maestro-web.js

Fixes a bug where the element title was checked for truthiness but was not then selected as the node id.

WebDriver: Use element title as id correctly

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

Fixes the following issues:
- Use specified duration instead of default 400 ms for relative swipe command
- Initialize `jsEngine` in `Orchestra.executeCommand` to avoid an unhandled exception thrown as part of executing repeat commands from Studio:
```
kotlin.UninitializedPropertyAccessException: lateinit property currentScope has not been initialized
```
This has been tested locally and I also update test case `078` to have a correct assertion.

Fix uninitialized jsEngine in Orchestra; Respect duration in relative swipe command

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

Set the all permissions to allow when executing
```
- launchApp
clearState: true
```
Tested on apps with permissions.
Permission prompts are not present on maestro cloud, but do happen on local maestro runs. By starting the flow with launchApp with clearState, the permissions will be in the same state both on cloud as on local runs.

Set all permissions to allow when launchApp with clearState

---

gradle/libs.versions.toml
maestro-client/build.gradle
maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-client/src/main/java/maestro/drivers/WebDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlOpenLink.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/084_open_browser.yaml
maestro-test/src/test/resources/085_open_link_auto_verify.yaml

1. Add openBrowser command separately for opening the browser for https/http link. Sometimes different apps intercept these links which cause unexpected behavior.
2. Add autoVerify flag on openLink command which will optionally auto verify opening HTTP links to user app and also agree the chrome agreement.
```
appId: com.chatloop.my
---
- openLink: 
link: https://something.com/linking
autoVerify: true
```
By default this flag is false.
Attaching internally.
https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1676539339478699

[MOB 1869] Auto verify opening deeplinks on Android

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Allow launching android apps with permission id's or as a group
For example, allowing read/write storage could be:
```
- launchApp:
permissions: storage
```
and for user permissions or which are not in list:
```
- launchApp:
permissions:
android.permission.BODY_SENSORS_BACKGROUND: allow
```

Allow launchApp with permissions on Android

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Clicking on just once button was missing in one of the cases when app name is present with multiple apps.

Just once in app element autoVerification

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/util/EnvUtils.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/util/Env.kt

- If no API key is present as an option and the user is **not** logged in, use whatever value stored in `MDEV_API_KEY` in the current shell instead.
- When running `maestro test` **locally**, inject all shell environment variables and make them available for commands. Note that for security reasons, the injected shell variables won't be sent along to Maestro Cloud when running `maestro cloud`.
Tested locally.

Read API key from shell; Decorate env with shell env vars

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-client/src/main/java/maestro/drivers/WebDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlClearState.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlLaunchApp.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/086_launchApp_sets_all_permissions_to_allow.yaml
maestro-test/src/test/resources/087_launchApp_with_all_permissions_to_deny.yaml
maestro-test/src/test/resources/088_launchApp_with_all_permissions_to_deny_and_notification_to_allow.yaml

Allow to set permissions in `launchApp`:
```
- launchApp:
permissions: { notifications: deny }
```
Tested on customer app flows.
* https://github.com/mobile-dev-inc/maestro/issues/133
* There is a difference in permission handling on maestro cloud vs maestro cli on iOS, this PR is a step to close that gap

Support for permission parameter on launchApp

---

maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Avoid javascript string parsing and javascript execution during value-setter,
by using rhino's api to wrap the java string and put it directly into the runtime's scope.
Ran the test suite which covers this code
Some customers have issues since 1.24.0, likely because their environment values are set to invalid javascript strings.

Enter values in the javascript engine by wrapping them

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-test/src/test/resources/089_launchApp_with_sms_permission_group_to_allow.yaml
maestro-test/src/test/resources/090_launchApp_with_permission_is_not_in_list.yaml

- add SMS group permission
```yaml
---
- launchApp:
permissions: sms
```
- add more tests
```bash
089_launchApp_with_sms_permission_group_to_allow.yaml
090_launchApp_with_permission_is_not_in_list.yaml
```
#889

add SMS group permission

---

maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/util/Env.kt

- Only inject shell env vars prefixed with `MAESTRO_`
- Also inject env vars when running `maestro cloud`, to avoid different results compared to running locally when Flows are depending on shell env vars.
Note that this changes the current behaviour, which is to inject _all_ env vars when running locally and _not_ propagate these env vars to Maestro Cloud.
Tested locally.

feat: update env var injection and propagate to cloud

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerOpenCommand.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-cli/src/main/java/maestro/cli/studio/DeviceScreenService.kt
maestro-cli/src/main/java/maestro/cli/studio/DevicesService.kt
maestro-cli/src/main/java/maestro/cli/studio/MaestroStudio.kt
maestro-cli/src/main/java/maestro/cli/studio/Models.kt
maestro-cli/src/main/java/maestro/cli/studio/ReplService.kt

- Make it possible to start Studio without a selected device
- Add a device api with three routes:
- `GET /api/devices` that returns connected devices as well as devices available for launch
- `GET /api/devices/selected` that returns the currently selected device if any
- `POST /api/devices/selected` that allows selecting a device via either `instanceId` or `modelId`
Tested locally

Add device API to allow listing and selecting devices

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-xcuitest-driver/src/main/kotlin/util/XCRunnerSimctl.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/installer/XCTestInstaller.kt

Stop a running XCTest runner before starting it.
Exception where the XCTest runner is restarted but was already running: "Failed to reach out XCUITest Server".

Stop XCTest runner before starting

---

maestro-client/src/main/java/maestro/drivers/WebDriver.kt

Because of a recent chrome update, when running the web driver we would get this error on our test runner machine:
```
org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Invalid Status code=403 text=Forbidden
java.io.IOException: Invalid Status code=403 text=Forbidden
at org.asynchttpclient.netty.handler.WebSocketHandler.abort(WebSocketHandler.java:92)
at org.asynchttpclient.netty.handler.WebSocketHandler.handleRead(WebSocketHandler.java:[11](https://github.com/foxtrotco/foxtrot-next/actions/runs/4426621340/jobs/7763296013#step:3:12)8)
at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
at …
```

Add argument for remote allow origins to WebDriver

---

maestro-xcuitest-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

Wait longer while the XCTest runner is being started manually

Make running XCUITest from Xcode easier

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt

- Manual
- longPressOn would display as "Tap" as command description. Now it correctly shows "Long press"

Adds proper text description for long press

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/api/EraseTextRequest.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/api/PressButtonRequest.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/api/PressKeyRequest.kt

Use the XCTest runner version of keyPress() buttonPress() and eraseText()
Ran customer flows and crafter flows which execute these commands.
IDB crashes when commands are executed on an app with a big view hierarchy. The XCTest runner implementation of these commands should also work on apps with big view hierarchies.

Use the XCTest runner version of keyPress() buttonPress() and eraseText()

---

maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/091_assert_visible_by_index.yaml

No new functionality or fixes, just ensuring that `assertVisible` indeed respects element index

Tweak: test that assertVisible respects index

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

This simplifies the setup:
* DriverClient already needs Installer to restart the service on error
* Device already needs DriverClient to perform the API calls
* With this change Device no longer needs to know about the Installer

Pass XCTestInstaller to XCTestDriverClient instead of XCTestIOSDevice

---

maestro-client/src/main/java/maestro/Filters.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

There are no straightforward APIs to hide the keyboard on iOS. This PR attempts to hide the keyboard as a user through maestro. Three attempts at how maestro tries hiding the keyboard:
1. Scroll with a small delta on y axis
2. Scroll with a small delta on x axis
3. Clicking on static texts XCUIElement
Tested on multiple client apps.

Hide keyboard on iOS

---

maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

Throwing a custom exception inside network interceptor makes OkHttpClient library logging it. To fix it we need to return an error response instead.

fix: Error shows on flow runs "Failed to reach out XCUITest Server"

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

* Add message and response body in case of shutting down studio as well failures while executing XCTest requests
* Set a timeout for hideKeyboard if the swipe or other calls with hierarchy, activeApp underneath fails for some reason
Tested locally with known apps.

Missing message response

---

maestro-cli/src/main/java/maestro/cli/App.kt

A simple quality of life change to update the upgrade instructions to contain the command for upgrading instead of a url to a page that has the command to upgrade, streamlining that process a bit.
This is a simple text change
None

Changed upgrade instructions to include command instead of url

---

maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

maestro used to try and spawn xctest runner on the 'booted' simulator device. When multiple or no simulator devices are booted, this operation may get maestro in a bad state.
By specifying the deviceId explicitly, the bad state can be avoided.
Tested manually
Potentially fixes https://github.com/mobile-dev-inc/maestro/issues/880

Use deviceId when spawning xctest worker to a device

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios-driver/src/main/kotlin/util/XCRunnerCLIUtils.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

when multiple simulators are launched, simctl command with booted parameter often fail

[iOS] runner app uninstall fails when multiple iOS simulators are launched

---

maestro-cli/src/main/java/maestro/cli/model/TestExecutionSummary.kt
maestro-cli/src/main/java/maestro/cli/report/JUnitTestSuiteReporter.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt
maestro-cli/src/test/kotlin/maestro/cli/report/JUnitTestSuiteReporterTest.kt

- I added test duration measurement when running a flow
- Test durations are displayed for each test in the CLI output (only when running a test suite)
- Test durations are added to the `testcase` element as a `time` attribute conforming to the [JUnit XSD](https://llg.cubic.org/docs/junit/)
- Ran the cli tests `:maestro-cli:test`
- Ran the integration tests `:maestro-tests:test` (These were failing for me unless I fixed a line in [ApkDebuggable.kt](https://github.com/mobile-dev-inc/maestro/blob/main/maestro-client/src/main/java/maestro/android/ApkDebuggable.kt#L47))
- Ran the `TestSuiteStatusView` main function
- Tested the build on my flows both in command line and with the junit reporter
- Typo in variable name
```
Running on emulator-5554
Waiting for flows to complete...
[Failed] Login …
```

Add test duration measurement and display

---

maestro-client/src/main/java/maestro/android/ApkDebuggable.kt

Test locally by running the maestro command
In [java17](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/FileSystems.html#newFileSystem(java.nio.file.Path,java.lang.ClassLoader)) there is two `newFileSystem` which will make the build failed with `Overload resolution ambiguity`

Fix "Overload resolution ambiguity" in Java 17

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlStartRecording.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/099_screen_recording.yaml

- This PR adds the `startRecording: <recording_path>` and `stopRecording` commands as suggested in #336 
- The recording logic was already implemented so it was quite easy to add
- Wrote an integration test
- Built maestro and ran it locally both on an Android emulator and an iOS simulator
Fixes #336

Add screen recording commands

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

Adds `--ios-version` flag to the CLI so the user can select which of the supported iOS versions they can run the Flow against. The error handling (what iOS versions are supported will be handled by the server).

Adding --ios-version flag to configure iOS version to run in Maestro Cloud

---

maestro-ios-driver/src/main/kotlin/util/IOSLaunchArguments.kt
maestro-ios-driver/src/test/kotlin/IOSLaunchArgumentsTest.kt

- Any string argument containing a column that's passed on iOS gets truncated
- This is especially annoying if you want to pass urls as a launch argument
- This PR fixes this bug
Sample flow with issue: 
```
- launchApp:
arguments: 
-url: http://example.com
```
In the AppDelegate: 
```
UserDefaults.standard.string(key: "url") // Value is 'http' instead of 'http://example.com'
```
It works fine on Android
- I introduced a failing test and fixed it

Fix iOS url arguments

---

gradle/libs.versions.toml
maestro-client/build.gradle
maestro-client/src/main/java/maestro/js/GraalJsEngine.kt
maestro-client/src/main/java/maestro/js/GraalJsHttp.kt
maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-client/src/main/java/maestro/js/RhinoJsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/GraalJsEngineTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/kotlin/maestro/test/JsEngineTest.kt
maestro-test/src/test/kotlin/maestro/test/RhinoJsEngineTest.kt
maestro-test/src/test/resources/102_graaljs.yaml
maestro-test/src/test/resources/102_graaljs_subflow.yaml

Enables opting in to use GraalJS instead of Rhino JS for javascript evaluation. GraalJS is fully ECMAScript 2022 compliant while Rhino JS only supports ES5.
This feature is experimental for now, but we intend to make GraalJS the default if all goes well.
> **Note**
> This only has an effect if present at the top-level flow. It is ignored when included in any subflows.
```yaml
jsEngine: graaljs
---
- inputText: ${null ?? 'foo'}
```
> **Warning**
> This env var will have no effect when running on Maestro Cloud. Use the Flow config above instead to opt into GraalJS on Maestro Cloud.
```shell
export MAESTRO_USE_GRAALJS=true
maestro test my-flow.yaml
```
There are some differences between the new `GraalJsEngine` and the current `RhinoJsEngine` implementation that are …

Implement Experimental GraalJsEngine

---

maestro-cli/src/main/java/maestro/cli/command/LogoutCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/AnsiResultView.kt
maestro-cli/src/main/java/maestro/cli/util/PrintUtils.kt

Some ansi formatted strings insert an extra space at the end:
This PR removes all places where an extra space is inserted due to ansi formatting.
Tested by running the samples locally

Remove extra space at end of input from ansi colored text

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestClient.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/XCTestInstaller.kt
maestro-utils/src/main/kotlin/SocketUtils.kt

This PR refactors the port number for `LocalXCTestInstaller` to allow a random port in case of not using a default port (22087). This PR still keeps the default port to avoid any compatibility issues.
`LocalXCTestInstaller` now returns the connection in terms of `XCTestClient`, to be used by the connection above. This keeps the connection contained and can be improved later on.
✅ Manual tests on ios samples
✅ Integrated tests ran

feat: create XCTestClient

---

samples/subflows/onboarding-ios.yaml

Currently the advanced example flow on iOS will only successfully run once, because the Wikipedia app remembers the selected options.
By setting `clearState: true`, the app state is erased, and the advanced flow can be ran multiple times without failing in the setup.
Tested locally

Clear state before running advanced example

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

- Close screen recording if it was left open after finishing an execution.
- Run a flow that triggers`startRecording` but never calls `stopRecording`.
- Verify the resulting video is not corrupted.
https://github.com/mobile-dev-inc/maestro/issues/1177

Close existing screen recording if it was left open.

---

maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

This PR adds the exception message and the stacktrace to the Fake Ok response when receiving an error from XCTest Server.
This should facilitate debug.

chore: add stacktrace and message to response

---

maestro-cli/src/main/java/maestro/cli/runner/CommandState.kt
maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/AnsiResultView.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/PlainTextResultView.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/UiState.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroConfig.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlOnFlowComplete.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlOnFlowStart.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-orchestra/src/test/resources/YamlCommandReaderTest/022_on_flow_start_complete.yaml
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/103_on_flow_start_complete_hooks.yaml
maestro-test/src/test/resources/103_setup.js
maestro-test/src/test/resources/103_teardown.js
maestro-test/src/test/resources/104_on_flow_start_complete_hooks_flow_failed.yaml

This PR implements two hooks that can be executed before and after each maestro flow, i.e. to execute some setup / teardown actions.
Example of how the API will look like:
```
appId: myId
onFlowStart:
- runFlow: setup.yaml
- runScript: setup.js
- <any other command>
onFlowComplete:
- runFlow: teardown.yaml
- runScript: teardown.js
- <any other command>
---
- launchApp
```
successful case:
https://github.com/mobile-dev-inc/maestro/assets/961175/49aa1ed7-2c75-4658-8c18-f00081be556c
failed case:
https://github.com/mobile-dev-inc/maestro/assets/961175/fd58cb97-9efb-4f46-b356-973bb0008ffb

setup / teardown hooks

---

maestro-ios-driver/src/main/kotlin/util/XCRunnerCLIUtils.kt

Save xcodebuild Log output from the xctest-runner into the OS level temporary directory.
By default, xcodebuild saves the xctest-runner Log output to DerivedData, where it will accumulate.
With this change, the Log output will be saved to the OS level temporary directory, which will be cleaned up by the OS when needed.
Tested locally
#1166

Log xctest xcodebuild output to system temp dir

---

maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

This PR adds a more generic retry interceptor, trying more aggressively to retry if XCTestServer fails to respond.

feat: add a more generic retry interceptor to XCTestDriverClient

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

This new constructor adds the possibility to initialize a default XCTestClient, this is useful if the client is already opened with another execution of Maestro.
✅ Tested locally running both maestro studio and test at the same time

fix: add secondary constructor to initialize a default XCTestClient

---

maestro-studio/web/src/components/commands/CommandRow.tsx
maestro-studio/web/src/components/design-system/input.tsx
maestro-studio/web/src/components/device-and-device-elements/ElementsPanel.tsx
maestro-studio/web/src/helpers/commandExample.ts

- Wrapped the element names in the sidebar so that the entire string is always visible
- Automatic focus on Search Input when the sidebar is opened
- Fixed the tap on input for focus
- Fixed the additional enters inside the command when "id" is too long (this issue is with copy/paste and exports)
- We were only showing elements having text or resourceId in the sidebar. I have added elements having hintText & accessibilityText to the list.
- While searching text highlight was case sensitive. Fixed this. (Search was working but highlighted was not working)
- Character 0 was not being searched in the sidebar, I made it work by adding a unique string

Studio feedbacks & improvements

---

maestro-client/src/main/java/maestro/js/GraalJsHttp.kt
maestro-client/src/main/java/maestro/js/JsHttp.kt
maestro-test/src/test/kotlin/maestro/test/RhinoJsEngineTest.kt

Hello Maestro team, this is my first PR to an open source repo so please let me know if I've missed anything 🙂
As it stands right now, [the response from an http request in maestro](https://maestro.mobile.dev/advanced/javascript/make-http-s-requests#response-object) only returns fields:
- `ok`
- `status`
- `body`
However there are use cases where the `headers` returned on a response are also needed.
This PR simply adds a `headers` property onto the response object.
Thankfully this is easy given that the okHttpClient under the hood exposes a way for us 🎉 
This now means in our JS scripts we can call something like:
**Script**
```
const response = http.get("https://google.com");
console.log(response.headers);
```
**Output (i.e the headers)** 
```
{
alt-svc=[h3=":443"; …
```

Feature: Add headers onto http response.

---

maestro-client/src/main/java/maestro/js/GraalJsHttp.kt
maestro-client/src/main/java/maestro/js/JsHttp.kt
maestro-test/src/test/kotlin/maestro/test/GraalJsEngineTest.kt
maestro-test/src/test/kotlin/maestro/test/JsEngineTest.kt
maestro-test/src/test/kotlin/maestro/test/RhinoJsEngineTest.kt

The ProxyObject.fromMap() method requires a ProxyObject, and we're giving it a Kotlin Map for the headers field. So when we're trying to access headers in GraalJS they are empty.
We should convert the headers to a Map object that GraalJS can work with. Since headers are multi-value, we will convert them to a Map where each key has a string with comma-separated values.
This PR also fixes the headers API, to be unified for GraalJS and RhinoJS, where value is a string (comma separated values in case of multiple values):
```
headers = Object(
"key1": "1,2"
)
```
and i.e. content-type can be parsed like that:
```
var contentType = response.headers['content-type'];
```
cc @jlwillo

[fix] Fix response headers mapping for GraalJS

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

The future is not needed any more since we have fixed swipe and scroll and also the animation problem we had with wait for app being idle.
Locally ✅

Removing future call from hideKeyboard to avoid leaks 

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/RecordCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/report/TestDebugReporter.kt
maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt

1. Give the option to configure debug flows output
2. By default it saves in .maestro under user directory
3. An extra option for maestro test and record command to configure the tests folder with --debug-output
https://github.com/mobile-dev-inc/maestro/issues/1100

Configure path for debugging flows output

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

When notifications are configured in workspace/config.yaml they will trigger on the result of the flow runs. Which is not always desired.
This PR allows to specify `--disable-notifications` on `maestro cloud`, which will request notifications of that upload to not be send.
Tested locally.

Add support for disabling notifications configured in config.yaml

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt

Currently we're seeing this message in case of 500 errors:
`Upload failed with status code 500, retrying...`
This PR implements logging the error message itself as well

Log error message in case of 500 errors during upload

---

maestro-studio/web/src/components/device-and-device-elements/DeviceWrapperAspectRatio.tsx

**_Issue:_** The device's size expanded disproportionately when the window was resized.
**_Solution:_** Adjusted the styling by setting `flex-grow` to `flex-1` and positioning inner elements as `absolute`.

Studio: Fixed device overflow on window resize

---

maestro-studio/web/src/components/device-and-device-elements/ActionModal.tsx

Reason - This will give more space to view the id for context.

Studio - Hide action buttons till command is hovered

---

maestro-studio/server/src/main/java/maestro/studio/DeviceScreenService.kt
maestro-studio/server/src/main/java/maestro/studio/Models.kt
maestro-studio/server/src/main/java/maestro/studio/ReplService.kt
maestro-studio/web/package-lock.json
maestro-studio/web/package.json
maestro-studio/web/src/api/api.ts
maestro-studio/web/src/api/mocks.ts
maestro-studio/web/src/helpers/models.ts
maestro-studio/web/src/pages/InteractPage.tsx
maestro-studio/web/storybook-assets/mockServiceWorker.js

* Maestro Studio can now run in multiple tabs simultaneously
* Improves Maestro Studio performance
* Custom long-polling was causing simultaneous API calls to hang (mostly in Chrome)
* Switching to Server-Sent Events instead
* In order to mock SSEs we need to upgrade MSW to the fetch release candidate version. Context: https://github.com/mswjs/msw/blob/feat/standard-api/MIGRATING.md#support-readablestream-mocked-responses

Use Server-Sent Events instead of custom long-polling in Maestro Studio

---

maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-studio/server/src/main/java/maestro/studio/DeviceScreenService.kt
maestro-studio/web/src/pages/InteractPage.tsx

This PR:
- adds compression for maestro studio screen refresh device screenshots to improve refresh performance
Some of the problems related to the issues mentioned [here](https://github.com/mobile-dev-inc/maestro/issues/805) might be resolved

Fix performance issues with maestro studio device refresh

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-client/src/test/java/maestro/xctestdriver/XCTestDriverClientTest.kt
maestro-ios-driver/src/main/kotlin/xcuitest/api/NetworkErrorHandler.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

1. Catching IOException in The `XCTestClient#ensureOpen` call which only caught connectException but driver is really going to be ready when it doesn't have any IOException on a call
2. Increase the retries to 5 instead, since I saw 4 is enough
3. Change call to expect instead of get() which gives null

Fix creating connections

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-orchestra/build.gradle
maestro-orchestra/src/main/java/maestro/orchestra/error/ValidationError.kt
maestro-orchestra/src/main/java/maestro/orchestra/workspace/WorkspaceExecutionPlanner.kt
maestro-orchestra/src/test/java/maestro/orchestra/workspace/WorkspaceExecutionPlannerErrorsTest.kt
maestro-orchestra/src/test/java/maestro/orchestra/workspace/WorkspaceExecutionPlannerTest.kt
maestro-orchestra/src/test/resources/workspaces/.gitignore
maestro-orchestra/src/test/resources/workspaces/010_global_include_tags/config.yaml
maestro-orchestra/src/test/resources/workspaces/e000_flow_path_does_not_exist/error.txt
maestro-orchestra/src/test/resources/workspaces/e001_directory_does_not_contain_flow_files/error.txt
maestro-orchestra/src/test/resources/workspaces/e002_top_level_directory_does_not_contain_flow_files/error.txt
maestro-orchestra/src/test/resources/workspaces/e002_top_level_directory_does_not_contain_flow_files/workspace/subdir/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e003_flow_inclusion_pattern_does_not_match_any_flow_files/error.txt
maestro-orchestra/src/test/resources/workspaces/e003_flow_inclusion_pattern_does_not_match_any_flow_files/workspace/FlowC.yaml
maestro-orchestra/src/test/resources/workspaces/e003_flow_inclusion_pattern_does_not_match_any_flow_files/workspace/config.yaml
maestro-orchestra/src/test/resources/workspaces/e004_tags_config_does_not_match_any_flow_files/error.txt
maestro-orchestra/src/test/resources/workspaces/e004_tags_config_does_not_match_any_flow_files/excludeTags.txt
maestro-orchestra/src/test/resources/workspaces/e004_tags_config_does_not_match_any_flow_files/includeTags.txt
maestro-orchestra/src/test/resources/workspaces/e004_tags_config_does_not_match_any_flow_files/workspace/ConfigExclude.yaml
maestro-orchestra/src/test/resources/workspaces/e004_tags_config_does_not_match_any_flow_files/workspace/ParameterExclude.yaml
maestro-orchestra/src/test/resources/workspaces/e004_tags_config_does_not_match_any_flow_files/workspace/config.yaml
maestro-orchestra/src/test/resources/workspaces/e005_single_flow_does_not_exist/error.txt
maestro-orchestra/src/test/resources/workspaces/e005_single_flow_does_not_exist/singleFlow.txt

* Proper error messages for empty workspaces
* Surface workspace validation errors before trying to connect to device when running `maestro test`
* Lay test fixture groundwork for future error improvements
This PR also changes the behavior when includeTags are specified in both config.yaml and as a command line option. Previously, in order for a flow to be included, it would need to match one of the config.yaml includeTags AND one of the command line includeTags. Even though this might be useful for some specific scenarios, this behavior is confusing and hard to explain. Now, in order for a flow to be included, it needs to match only one includeTag regardless of where the includeTag was specified.
```
Flow path does not exist: {PROJECT_DIR}/src/test/resources/workspaces/e000_flow_path_does …
```

Error message improvements

---

maestro-cli/src/main/java/maestro/cli/view/ErrorViewUtils.kt
maestro-orchestra/src/main/java/maestro/orchestra/error/SyntaxError.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-orchestra/src/test/resources/workspaces/e006_single_flow_invalid_string_command/error.txt
maestro-orchestra/src/test/resources/workspaces/e006_single_flow_invalid_string_command/singleFlow.txt
maestro-orchestra/src/test/resources/workspaces/e006_single_flow_invalid_string_command/workspace/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e007_single_flow_malformatted_command/error.txt
maestro-orchestra/src/test/resources/workspaces/e007_single_flow_malformatted_command/singleFlow.txt
maestro-orchestra/src/test/resources/workspaces/e007_single_flow_malformatted_command/workspace/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e008_subflow_invalid_string_command/error.txt
maestro-orchestra/src/test/resources/workspaces/e008_subflow_invalid_string_command/workspace/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e008_subflow_invalid_string_command/workspace/subflow/SubFlow.yaml
maestro-orchestra/src/test/resources/workspaces/e009_nested_subflow_invalid_string_command/error.txt
maestro-orchestra/src/test/resources/workspaces/e009_nested_subflow_invalid_string_command/workspace/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e009_nested_subflow_invalid_string_command/workspace/subflow/SubFlowA.yaml
maestro-orchestra/src/test/resources/workspaces/e009_nested_subflow_invalid_string_command/workspace/subflow/SubFlowB.yaml
maestro-orchestra/src/test/resources/workspaces/e010_missing_config_section/error.txt
maestro-orchestra/src/test/resources/workspaces/e010_missing_config_section/workspace/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e011_missing_dashes/error.txt
maestro-orchestra/src/test/resources/workspaces/e011_missing_dashes/workspace/Flow.yaml
maestro-orchestra/src/test/resources/workspaces/e012_invalid_subflow_path/error.txt
maestro-orchestra/src/test/resources/workspaces/e012_invalid_subflow_path/workspace/Flow.yaml
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

Example error message:
```
Failed to parse file: {PROJECT_DIR}/src/test/resources/workspaces/e006_single_flow_invalid_string_command/workspace/Flow.yaml:3
Cannot construct instance of `maestro.orchestra.yaml.YamlFluentCommand`, problem: Invalid command: "invalidCommand"
```

Include file name and line numbers in parsing error messages

---

maestro-client/src/main/resources/maestro-web.js

`maestro-web.js` `traverse` uses "data-testid" as an additional fallback for "resource-id", because [that's what react-native-web uses](https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/createDOMProps/index.js#L813) for [testID](https://reactnative.dev/docs/view#testid).
verified that the below Maestro script, which depends on an ID selector and works with React Native for iOS and Android, now works on web.
```
appId: "http://localhost:8090"
#appId: "com.trulysmall.expenses"
---
- launchApp:
clearState: true
- tapOn: "Get Started"
- tapOn: "Email"
- inputText: "adam.hari+"
- "inputRandomNumber"
- inputText: "@kashoo.com"
- tapOn: "Full name"
- inputText: "Maestro E2E"
- tapOn: "Password.*"
- inputText: "test123456"
- "hideKeyboard"
- tapOn:
id: …
```

feat: support id selection for testID with react-native-web

---

maestro-studio/web/src/components/device-and-device-elements/SelectedElementViewer.tsx

Fixed the Dark mode colors for recently added element id.

fixed dark mode for element id

---

maestro-cli/src/main/java/maestro/cli/util/EnvUtils.kt

Previously we used `uname -m` to detect OS architecture but MacOS Rosetta was interfering. Replaced with `sysctl` which is more reliable.
More context on the issue https://github.com/JuliaLang/juliaup/pull/701/files

Fixes architecture detection

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

[FlyingFox](https://github.com/swhitty/FlyingFox) (the library that we use for XCTest HTTP server) implements loopback address using Darwin POSIX address:
```
Darwin.sockaddr_in6(
sin6_len: UInt8(MemoryLayout<sockaddr_in6>.stride),
sin6_family: sa_family_t(AF_INET6),
sin6_port: port.bigEndian,
sin6_flowinfo: 0,
sin6_addr: in6addr_loopback,
sin6_scope_id: 0
)
```
Server is listening on IPv6 all the time and is able to resolve IPv4 connections correctly if `::1 localhost` is present inside `etc/hosts`, however fails if it doesn't.
[SwiftNIO](https://github.com/apple/swift-nio) has its own [convenience method](https://swiftinit.org/docs/swift-nio/niocore/socketaddress.makeaddressresolvinghost(_:port:)) for this case. We could consider in the future to migrate to …

[fix] xcuitest.XCTestDriverClient$XCTestDriverUnreachable issues

---

maestro-client/src/main/java/maestro/js/GraalJsHttp.kt
maestro-client/src/main/java/maestro/js/JsHttp.kt
maestro-client/src/main/java/maestro/utils/HttpUtils.kt
maestro-client/src/test/java/maestro/utils/HttpUtilsTest.kt
maestro-test/src/test/kotlin/maestro/test/JsEngineTest.kt

This PR adds support for multipart form data file upload.
The feature can be used to prepare data on the backend before running e2e tests on mobile.
Usage is simple. Instead of a `body` object, we can define `multipartForm` with as many fields as we want. We can also upload multiple files in one request by using many objects with `filePath` properties. `filePath` is required for the files. `mediaType` is optional. If `multipartForm` is available in a request then `body` will be ignored.
PR with the updated docs can be found here: https://github.com/mobile-dev-inc/maestro-docs/pull/28
``` js
function uploadFile() {
const filePath = ``;
const url = ``;
const response = http.post(url, {
multipartForm: {
"uploadType": "test",
"data": {
"filePath": filePath,
"mediaType": "text/csv"
}
}, …
```

Add support for multipart form data file upload

---

maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

[AppleSimulatorUtils](https://github.com/wix/AppleSimulatorUtils) has some issues with setting permissions on iOS17 and newest Xcode 15 SDK. This PR migrates setting location permission logic (which was the main source of `Unable to clear state for app xxx.xxx` errors) to simctl.
https://github.com/mobile-dev-inc/maestro/issues/1463

[fix] set location permission is broken on iOS

---

maestro-client/src/test/java/maestro/xctestdriver/XCTestDriverClientTest.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

Adding a new crash case found during tests.
The message "Error getting main window Unknown kAXError value -25218" also means that app is crashed or force stopped.

fix: adds new crash case

---

maestro-orchestra/src/main/java/maestro/orchestra/workspace/ExecutionOrderPlanner.kt
maestro-orchestra/src/main/java/maestro/orchestra/workspace/WorkspaceExecutionPlanner.kt
maestro-orchestra/src/test/java/maestro/orchestra/workspace/ExecutionOrderPlannerTest.kt

executionOrder right now is unnatural, and this PR proposes a better API/understanding for it. This PR also improves the error message to contain all missing flows, not only the first it encounters.
> This is not a breaking change, as working workspaces will be kept working.
Suppose you have 4 flows specified in the `executionOrder`:
A -> B -> C -> D (D depends on C, which depends on B, which depends on A)
However, if you decide to execute only the first 3 (A, B, C) the current behavior is to error out. This PR enables this execution since the missing flow is _AFTER_ the ones present, in other words, the ones being requested to execute does not have a dependency on the missing one (D).
Suppose you have 2 flows specified in the `executionOrder`:
A -> B
However, if you decide to execute the …

feat: Improve executionOrder planning

---

maestro-client/src/main/java/maestro/Errors.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Throws custom exception instead of timeout exception since that can lead to misclassification of exceptions

fix: throws different exception instead of `TimeoutException` for driver startup

---

maestro-cli/src/main/java/maestro/cli/command/StartDeviceCommand.kt
maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-client/src/main/java/maestro/utils/LocaleUtils.kt
maestro-client/src/test/java/maestro/utils/LocaleUtilsTest.kt

This PR moves logic related to device locale validation to the `maestro-client` module to be able to reuse in in Maestro Cloud

Move device locale validation logic to maestro-client

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

This PR adds a new parameter to `maestro cloud` command to be able to set device locale for device to execute a flow on.
Example usage:
`maestro cloud --device-locale de_DE <app_binary_path> <flows_path>`

Add support for deviceLocale param in `maestro cloud`

---

maestro-cli/src/main/java/maestro/cli/device/DeviceCreateUtil.kt
maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

This PR fixes awaitShutdown logic (which we use for `reboot` operation), considering that deviceId might be lowercase and state might be `Shutting Down`

[iOS] Fix awaitLaunch and awaitShutdown logic

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

This PR makes awaitLaunch more robust - no timeout needed anymore, bootstatus is better in this case, since it waits until Springboard is fully launched, while just tracking the Booted state from `simctl list` doesn't

Make simulator reboot logic more robust

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt

Improves device specs message to include --device-locale parameter. Example UI:

Improve device specs message for maestro cloud command to include device locale

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/ElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/114_child_of_selector.yaml

When we are reusing a component/ui inside different different UI. Then to correctly identify which component to select we are adding this `childOf` selector
eg we have a button element and its id is `proceed`. Now this button is used by two UI component in the same page. Now we have two view components id: add_to_cart and buy_now but the inner button have same id `proceed`. So if placement of  these two UI element is dynamic it becomes very difficult to correctly select which one represents add_to_cart and which represents buy_now to tap.
`childOf` selector into rescue. `childOf` selector tells maestro to select id or text which is child of provided selector.
eg if we want to tap on buy now button we can easily write.
```
tapOn:
text: "proceed"
childOf:
- id: "buy-now"
```
this will first …

childOf selector

---

maestro

This PR fixes the shebang in the maestro script to work on systems where `/bin/bash` doesn't exist (e.g. NixOS).
Instead it now uses `/usr/bin/env` to lookup a bash binary in PATH.

fix shebang in maestro script

---

maestro-client/src/main/java/maestro/KeyCode.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/034_press_key.yaml

Added the following pressKeys for remote TV:
- Remote System Navigation Up
- Remote System Navigation Down
- Remote Button A
- Remote Button B
- Remote Menu
- TV Input
- TV Input HDMI 1
- TV Input HDMI 2
- TV Input HDMI 3
Some remote keys weren't added to the codebase.

[TV Remote] Add extra remote keys for TV

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt

When the CLI calls Maestro Cloud backend to get the status of the upload it's not using the retry mechanism for 404 responses. I'm expanding the retry to also handle 404s

Extending retry to handle 404 in upload status call

---

maestro-ios-driver/src/main/kotlin/util/XCRunnerCLIUtils.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

1. Properly release resources in case of retries
2. Clean directory instead of deleting the temp directory 
3. Add flag to enable/disable xctest logging

Fix cleaning up retries in iOS driver

---

maestro-client/src/main/java/maestro/js/GraalJsEngine.kt
maestro-client/src/main/java/maestro/js/Js.kt
maestro-client/src/main/java/maestro/js/RhinoJsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Add a `platform` property to the `maestro` object in JavaScript, so as to determine iOS or Android at runtime.
```
output.welcomeMessage = "Your app is running on " + maestro.platform
```
Previously, an app that requested a few permissions would have lots of this:
```
- tapOn: "Enable Location"
- runFlow:
when:
platform: 'Android'
commands:
- assertVisible: "Allow access to this device's location?"
- tapOn: "While using the app"
- runFlow:
when:
platform: 'iOS'
commands:
- assertVisible: "This app uses your location to show you information about your local environment."
- tapOn: "Allow While Using App"
- assertVisible:
id: "location_permission_true"
```
I wanted to set the strings in JavaScript, but this would require prepending the flow with something like:
```
- runFlow:
when:
platform: …
```

Add 'maestro.platform' for javascript to determine platform

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Since API 34, screen recording duration limit has been extended [from 3 minutes to 30 minutes](https://issuetracker.google.com/issues/236721231). However, `--time-limit 0` needs to be passed to the adb `screenrecord` command (by default is 180).
- Managed to record a flow of 7 minutes on a device running on API 34
- Running the same flow on API 33 produced the same output as before (recording stopped at 3 minutes)

Remove screen record time limit for Android devices running on API levels >= 34

---

maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

I think `xcTestDriverStatusCheck` may return a response object with an error response or throw. In `isChannelAlive`, where we care about _whether_ channel is alive we should treat an exception as an `isChannelAlive = false`.
I verified this is valid Kotlin code and looks similar to `ensureOpen`.
I've run into the "Protocol family unavailable" after a CI-run test job fails to connect to XCUITest server. I believe the `xcTestDriverStatusCheck` should be wrapped with `try-catch`, as it is in `ensureOpen()`.

Fix "Protocol family unavailable" on rerun after failure

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Errors.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-client/src/main/java/maestro/drivers/WebDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSetAirplaneMode.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlToggleAirplaneMode.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/115_airplane_mode.yaml

add a new command for controlling the airplane mode of android devices.
ran the following flow on android 27 and 28 emulators:
```yaml
appId: org.wikipedia
---
- launchApp
- setAirplaneMode: disable
- setAirplaneMode: enable
```

feat: allow airplane mode control

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/report/TestDebugReporter.kt

Continuing #1445 
Fixes #1427 
Adding a `--flatten-debug-output` switch that will remove the datetime folder, as well as `/.maestro/tests/` from the path, leaving the debug output exactly where the user defined.
(Updated with feedback from previous PR to remove 
Added a new option `--flatten-debug-output` to the `test` command in `maestro-cli` to simplify the test output folder structure for CI environments. Updated the `TestDebugReporter` class to handle this option and generate the output path accordingly.
I'm using a simple flow to force an error:
```
appId: com.example
---
- assertTrue: 
condition: ${ 1 === 2 }
label: 1 is the same as 2
```
No params:
```
⇒ ./maestro test scratch.yaml 
Running on emulator-5554      
║                            
║  > Flow                    
║ …
```

Add command-line switch to omit folders from debug output

---

.github/workflows/test.yml
gradle/wrapper/gradle-wrapper.properties

It's a security best practice to verify the Gradle distribution used within the project to protect against a supply-chain-style attack. These have been observed in the wild previously and are easily mitigated through the use of the `distributionSha256Sum` Gradle property [^1]
This PR adds the expected Gradle distro verification for Gradle Wrapper 7.6 by calling the `gradlew wrapper` task as follows:
```sh
./gradlew wrapper --gradle-version=7.6 --distribution-type=bin --gradle-distribution-sha256-sum=7ba68c54029790ab444b39d7e293d3236b2632631fb5f2e012bb28b4ff669e4b
```
The checksums for Gradle distributions are available via Gradle's website[^2] and the above can be verified.
> [!IMPORTANT]
> Post-merging, whenever the Gradle version is updated, the above command should be repeated with the …

Add Gradle distribution verification to project

---

.github/workflows/close-inactive-issues.yml
.github/workflows/lock-closed-issues.yml

Automate triage process a bit.
Add 2 new periodic scheduled GitHub Actions workflows:
- `close-inactive-issues` - close issues that have had the "waiting for customer response" label for too long (configurable)
- `lock-closed-issues` - lock issues that have been closed for long enough (configurable). to prevent people from "reviving" old issue from the graveyard. There are no downsides to creating a new issue with up-to-date info and referencing the old, closed one.
Generally, the new triage workflow I propose is:
1. Open a new issue, read through it, make sure it is reproducible, or at least we know what's happening
2. If it's not reproducible/we don't know what's happening, ask for more information and assign the **waiting for customer response** label
3. When the user/customer …

Add some automation to help manage GitHub issues

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/ShowHelpMixin.kt
maestro-cli/src/main/java/maestro/cli/command/BugReportCommand.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/DownloadSamplesCommand.kt
maestro-cli/src/main/java/maestro/cli/command/LoginCommand.kt
maestro-cli/src/main/java/maestro/cli/command/LogoutCommand.kt
maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/command/QueryCommand.kt
maestro-cli/src/main/java/maestro/cli/command/RecordCommand.kt
maestro-cli/src/main/java/maestro/cli/command/StartDeviceCommand.kt
maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt

This tiny PR adds makes the `-h`/`--help` flag work for the root command and all subcommands.
It's a small change so I tested it locally, and it works.
n/a

Add `--help` flag to all commands

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt

change `result` to `resultSingle` for return and calculate `passed` test
Run single maestro test
`maestro test testFile.yaml`
since `passed` counts the number of the exit code of `resultSingle` `val passed = results.sumOf { it.first ?: 0 }`,
if the test is passed, the exit code will be 0 and failed 1.
the calculation will be incorrect. hence if we revert the value, the calculation will be correct.

Fix exit code for single test

---

.github/ISSUE_TEMPLATE/bug_report.yaml

I remembered about the 2 options that are useful for debugging where actually a UI testing framework tapped.
Follow-up of #1805 
Demo:

Small update to bug report template

---

maestro-cli/build.gradle.kts

We need openjdk as dependency in our formula.
-
related to #1513

brew: bring back `openjdk` as dependency

---

maestro-cli/src/main/java/maestro/cli/analytics/Analytics.kt
maestro-cli/src/main/java/maestro/cli/util/IOSEnvUtils.kt

**Could not reproduce** #1850, but this should fix it anyway.

Ignore all failures while uploading analytics data

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt

To help pinpoint root cause of #1856
This is how it will look like:

ApiClient: print stack trace when retry fails

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt

I think this is because of the shards race condition
So by adding a delay will fix the race condition
https://github.com/mobile-dev-inc/maestro/issues/1853 Unable to run parallel/sharded tests on Android

Fix Android Parallel/Shards Race Condition

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt

`maestro cloud`: gracefully handle run cancellation by user

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

fyi @amanjeetsingh150 @igorsmotto

Add new feature request template

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios/README.md

Maestro doesn't use `idb` in any way since [v1.31.0](https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#1310).

Remove all mentions of idb

---

maestro-studio/web/package-lock.json

Bump caniuse to vLatest via the recommended `npx update-browserslist-db@latest`
`./maestro studio`  works
n/a

Bump caniuse to latest for maestro-studio web

---

.github/workflows/test-e2e.yaml

Both GitHub Actions ([ReactiveCircus'](https://github.com/ReactiveCircus/android-emulator-runner) and [Malinskiy's](https://github.com/Malinskiy/action-android) for setting Android emulator don't work for us, because they don't allow for specifying a concrete version of Android Command-line Tools to install. And we nee to install Android CLT v8, because it's the latest version that works on Java 8, which is Maestro's minimal support target.

GitHub Actions: install Android SDK and set up AVD manually

---

.github/workflows/test-e2e.yaml

We cannot have `test-cloud` run always on user-submitted PRs, unless we want to risk exposing our secrets.
I decided to remove `test-cloud` job for this reason.
Will re-add it to run on some other kind of event.
https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

Remove test-cloud job

---

.github/workflows/test-e2e-prod.yaml
.github/workflows/test-e2e.yaml

was always failing because of a missing `\` in shell cmd

Fix "E2E prod" workflow

---

.github/workflows/test-e2e.yaml

dont fail e2e test when ending screenrecord fails

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt

- Change the error message depending on the above condition
- `./gradlew test`
- `./maestro-cli/build/install/maestro/bin/maestro test --format=JUNIT --continuous flow.yaml`
Fixes #1623

Fix wrong error message

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

- Delete temp APKs after being done using them
- `./gradlew test`
- Check presence of apks in tmp folder after cleaning it up and running a flow test
```
> ls $TMPDIR*.apk
/var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-app10071856759043844538.apk    /var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-server13015259718004766817.apk
/var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-app10167667838027668975.apk    /var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-server13421232218955671026.apk
/var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-app10340836042534871539.apk    /var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-server13852331780224097929.apk
/var/folders/5b/3tmqgg6n74s6gmg1980h87k40000gn/T/maestro-app10876012227926208134.apk …
```

Delete apks after using them

---

maestro-client/src/main/java/maestro/drivers/WebDriver.kt

This is a workaround for the `WebDriver` problem described in #1936. We are filling a login form and press the login button. During that navigation there's a short time where the content description is `null` which results in a forced crash.
With this workaround we try again to fetch the content description for a limited time until we finally give up.
Tested locally with Chrome `128.0.6613.85`.
Closes #1936.

WebDriver: Retry fetching content description

---

.github/workflows/test-e2e.yaml

Motivated by https://github.com/mobile-dev-inc/maestro/actions/runs/10646443357/job/29513363306?pr=1955, which had some bug and was running for 6 hrs (maximum run time)

Actions: add timeouts

---

maestro-client/src/main/java/maestro/android/AndroidAppFiles.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

I fixed a whole lot of stuff that was wrong with the `autoVerify`. It should now work as expected.
> [!NOTE]
> I cherry picked the commit from #1998 locally as I seemed to stumble on that same issue in other places as I tested
- I started investigating this #1956 issue. It was pretty straightforward to reproduce and fix.
- The origin is due to the fact that the reading of the app name to tap on the right cell of the Chooser is done through `apkMeta.name` 
- This value which contains the value defined in `<application android:label="name">` in the Manifest. Which obviously is not mandatory, not guaranteed to be there, and even better, not what the chooser shows as value
- The fix was simply to check the nullability of the value and throw if it's nullable (because it's a `String!` from …

Fix android open link verify

---

.github/workflows/test-e2e.yaml

The artifacts stopped appearing.

debug maestro-e2e-output not being present when tests fail

---

maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/util/Env.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/028_env.yaml
maestro-test/src/test/resources/041_take_screenshot.yaml
maestro-test/src/test/resources/064_js_files.yaml
maestro-test/src/test/resources/064_script.js
maestro-test/src/test/resources/064_script_alt.js
maestro-test/src/test/resources/099_screen_recording.yaml

- Set `FILENAME` env value to the flow file's name
- This happens only in the context of the test and does not alter the system env
I updated 2 of the integration tests to use the `FILENAME` env var and check their correct naming
Run ./gradlew :maestro-test:test
Run ./gradlew :maestro-orchestra:test
Run ./gradlew :maestro-orchestra-models:test
Fixes #1616

Add filename to env

---

maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandTest.kt

- Make `MaestroCommand#toString` way shorter and thus all logs and test results more readable
- Basically only keep the arg name for the single non null `Command` inside the `MaestroCommand`
- Added unit tests
None

Make MaestroCommand toString more concise

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt

- Add broadcast option to test command
- This supersedes `--shards` but respects `--device`
- It runs all the flows on all the available devices 
- This PR will be conflicting with #1953 quite a lot
- Launch two devices and run `maestro test -b` on a folder with multiple flows
- Make sure all flows run once on each device
Fixes #1844

Add broadcast option to test command

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/update/Updates.kt
maestro-cli/src/main/java/maestro/cli/util/ChangeLogUtils.kt
maestro-cli/src/test/kotlin/maestro/cli/util/ChangeLogUtilsTest.kt

- Fetch, the changelog from Github's `CHANGELOG.md`
- Filter the changes related to the proposed version
- Format them to be suitable for CLI display (remove links, bold and keep only top-level bullets)
- Hardcoded some versions as proposed for update and built the project
```
╭───────────────────────────────────────────────────────────────────────────╮
│                                                                           │
│   A new version of the Maestro CLI is available (1.37.9).                 │
│                                                                           │
│   See what's new:                                                         │
│   https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#1379   │
│ …
```

Fetch, format and display changelog in the CLI update message

---

e2e/workspaces/demo_app/commands_optional_tournee.yaml
e2e/workspaces/demo_app/fail_fast.yaml
e2e/workspaces/demo_app/fail_not_found.yaml
e2e/workspaces/demo_app/relatives.yaml
maestro-orchestra-models/src/main/java/maestro/orchestra/ElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt

The selector-level `optional` argument has been superseded by the command-level `optional` argument in #1946.
This PR is a follow up of #1946 (specifically, [this comment](https://github.com/mobile-dev-inc/maestro/pull/1946#issuecomment-2329230482))

Remove `optional` field from selectors

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt

```
> maestro test
Flow directories do not contain any Flow files:
```
```
> maestro test
Missing required parameter: '<flowFiles>'
Usage: maestro test [...]
```

Fix flow files arity

---

maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

Cloud command logs from `WorkspaceExecutionPlanner` is getting output on terminal. Install the debug reporter to output on file instead.
Locally running maestro cloud command

fix: install debug reporter in maestro cloud command

---

.github/workflows/test-e2e.yaml

Forked Bartek's scripts [here](https://github.com/mobile-dev-inc/bartek-scripts) so we freeze the repo and control it ourselves and don't end up with a broken workflow due to some changes in the repo in the future.

fix: use own fork of scripts in e2e test

---

maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Reinstall the app and then launch it instead of manually trying to delete app state folders, which should improve the experience when relying on clear state to have a completely blank slate in the app.
Relates to #1601

fix: reinstall ios app to clear state reliably

---

e2e/workspaces/demo_app/scrollUntilVisible_timeout.yaml
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-test/src/test/resources/117_scroll_until_visible_speed.js

The `timeout` in ScrollUntilVisibleCommand should be interpreted as milliseconds: https://maestro.mobile.dev/api-reference/commands/scrolluntilvisible
This was broken by https://github.com/mobile-dev-inc/maestro/pull/2023.
Updated and ran tests
Fixes https://github.com/mobile-dev-inc/maestro/issues/2108

Fix timeout unit in ScrollUntilVisibleCommand

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-studio/server/src/main/java/maestro/studio/InsightService.kt
maestro-utils/src/main/kotlin/Insight.kt
maestro-utils/src/main/kotlin/Insights.kt
maestro-utils/src/main/kotlin/InsightsInterface.kt
maestro-utils/src/test/kotlin/InsightTest.kt

`Insights` is a CLI-only concept. We've seen this implementation causing problems on the cloud. This PR provides a noop implementation to Insights by default so that we don't use it on cloud.
For CLI the real implementation is passed so that behavior of CLI remains unchanged
Locally running a command that raises insight. Tapping on optional view that's not there.

fix: use noop insights by default on maestro

---

.github/workflows/test-e2e.yaml
e2e/run_tests
e2e/workspaces/demo_app/commands/assertNotVisible.yaml
e2e/workspaces/demo_app/commands/assertTrue.yaml
e2e/workspaces/demo_app/commands/assertVisible.yaml
e2e/workspaces/demo_app/commands/back.yaml
e2e/workspaces/demo_app/commands/copyTextFrom.yaml
e2e/workspaces/demo_app/commands/eraseText.yaml
e2e/workspaces/demo_app/commands/evalScript.yaml
e2e/workspaces/demo_app/commands/extendedWaitUntil.yaml
e2e/workspaces/demo_app/commands/hideKeyboard.yaml
e2e/workspaces/demo_app/commands/inputRandomEmail.yaml
e2e/workspaces/demo_app/commands/inputRandomNumber.yaml
e2e/workspaces/demo_app/commands/inputRandomPersonName.yaml
e2e/workspaces/demo_app/commands/inputRandomText.yaml
e2e/workspaces/demo_app/commands/inputText.yaml
e2e/workspaces/demo_app/commands/killApp.yaml
e2e/workspaces/demo_app/commands/launchApp.yaml
e2e/workspaces/demo_app/commands/pasteText.yaml
e2e/workspaces/demo_app/commands/pressKey.yaml
e2e/workspaces/demo_app/commands/repeat.yaml
e2e/workspaces/demo_app/commands/runFlow.yaml
e2e/workspaces/demo_app/commands/runScript.js
e2e/workspaces/demo_app/commands/runScript.yaml
e2e/workspaces/demo_app/commands_tour.yaml
e2e/workspaces/demo_app/fail_launchApp.yaml
e2e/workspaces/demo_app/fail_launchApp_nonDefault.yaml
e2e/workspaces/demo_app/fail_visible.yaml
e2e/workspaces/demo_app/fail_visible_extended.yaml

Adds additional e2e tests:
* A tour of _most_ commands and their options
* A few additional expected failure cases
* `maestro test e2e/workspaces/demo_app/commands_tour.yaml`
* See the CI run :)

More e2e tests

---

example/build.gradle.kts
gradle/libs.versions.toml
maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/util/ChangeLogUtils.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-client/src/main/java/maestro/js/GraalJsEngine.kt
maestro-client/src/main/java/maestro/js/RhinoJsEngine.kt
maestro-client/src/main/java/maestro/mockserver/MockInteractor.kt
maestro-client/src/test/java/maestro/xctestdriver/XCTestDriverClientTest.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt
maestro-utils/build.gradle.kts
maestro-utils/src/main/kotlin/HttpClient.kt
maestro-utils/src/main/kotlin/Metrics.kt

The idea here is to introduce micrometer management across the board, starting w/ individual commands on ios and android. This will allow us to identify potential bottlenecks, errors at the command level, etc
The default implementation is a noop - it won't collect or send metrics anywhere. Users of maestro (eg robin itself) can hook them up so we get metrics for tests that run in the platform.
The idea is to also auto-instrument http requests (using okhttp), such that we can tell cases where retries are happening more than they should, etc

[RFC] measurement for device commands

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlScrollUntilVisible.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSwipe.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-orchestra/src/test/resources/YamlCommandReaderTest/027_waitToSettleTimeoutMs.yaml

Adding `waitToSettleTimeoutMs` to the swipe commands that do waitForAppToSettle call. This is to control the wait time if there are repeatable animations on the screen. 
Using this option would help users to wait less on the screens where app is settled but have repeatable animations.

fix: add waitToSettleTimeOut on swipe commands

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlRetry.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/119_retry_commands.yaml

Adds a retry command to retry a set of commands either inline or from a file. This helps to retry in case of known flakiness.
- Associates with a retry command so that it's easy to know where flakiness is
- Raise a warning insight for local CLI when execution is retried.
API:
```
- retry:
label: "Go to Cart screen (Flaky crash due to analytics SDK)"
maxRetries: 3
commands:
- scroll
- tapOn:
text: Button
waitToSettleTimeoutMs: 40
- scroll
```

feat: add retry functionality

---

maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

This is done because with the current 15 seconds driver was failing to setup sometime.
Keeping to 2 minutes which I've noticed being sufficient when we use maestro on CI.

fix: adjust server timeout to longer duration

---

.github/workflows/test-e2e.yaml
e2e/workspaces/no-app/README.md
e2e/workspaces/no-app/environment-variables.yaml
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt

Fixes environment variables when using a Test Suite (a folder, rather than an individual run)
* Run locally
* Added an E2E test
Fixes #2101

Fix environment variables for multi-flow runs

---

maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

In some cases (eg a fresh ios16 simulator), the Keychains folder doesn't actually exist, so deleting it returns a non-zero status code (which bubbles up as an exception).
This prevents that by not deleting if it doesn't exist

don't try to rm folder that doesn't exist

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt

Removing private access modifier from timeout field
Private modifier on timeout field is preventing the field to be populated on deserialization.

fix: assert condition command timeout parsing

---

CHANGELOG.md
maestro-cli/src/test/kotlin/maestro/cli/util/ChangeLogUtilsTest.kt

Tests are failing on main right now because the current version number isn't present in the changelog.
Worse, the test isn't failing - it's throwing an NPE instead.
This fixes both.

Fix changelog and accompanying test

---

maestro-cli/src/main/resources/logback-test.xml

Adding a logback.xml file to maestro-cli main folder
We were receiving a very unpleasent message on every maestro command
```
07:52:08.527 [pool-1-thread-1] DEBUG io.micrometer.common.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
1.39.7
```
Since the logback.xml only existed in the test folder. Now that we have it on main as well, things are back on track

fix(logback): Adding logback.xml to maestro-client main to avoid DEBUG messages on every command

---

maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-ios-xctest-runner/maestro-driver-iosUITests/Routes/Handlers/ViewHierarchyHandler.swift

When there is null hierarchy, 
```val error = mapper.readValue(responseBodyAsString, Error::class.java)```
fails, and we don't get the status code and error message. Added a warn log before it so that we can know the status code and error message.

chore: added log for null hierarchy

---

maestro-client/src/main/java/maestro/drivers/WebDriver.kt

Injecting launch arguments as top-level JS variables

Injecting launch arguments to web page

---

e2e/workspaces/wikipedia/android-advanced-flow.yaml
e2e/workspaces/wikipedia/ios-advanced-flow.yaml
e2e/workspaces/wikipedia/subflows/onboarding-android.yaml
e2e/workspaces/wikipedia/subflows/onboarding-ios.yaml

There were 2 issues with optional commands, this PR creates tests for the issues:
1. The optional flag on the selector was removed that broke deserialization and the change was not backward compatible.  The optional flag on the selector was removed from the test itself which prevented catching this regression. After observing this issue, the optional flag from selector is now deprecated.
2. Optional flags now throw command skipped exception. This was handled for the commands present in main flow but was missing in composite commands like runFlow. The addition to subFlow is suppose to catch those problem.

chore: add e2e tests for optional

---

maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Adds finer-grained logs for the set permissions operations performed using simctl and applesimutils. We've observed instances where applesimutils fails to set permissions, which can lead to another issue of not setting location permissions. 
This PR also decouples the simctl and applesimutil permission so that they don't couple each other.

Improve set permissions logs and avoid affecting location permissions

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Whenever you used something like `runScript: myscript.js` and the script contained a `console.log`, then you needed to go find the log line in the logs here
```
20:08:50.313 [ INFO] maestro.cli.runner.MaestroCommandRunner.invoke: Run loggingInJS_simple.js metadata CommandMetadata(numberOfRuns=null, evaluatedCommand=MaestroCommand(runScriptCommand=RunScriptCommand(script=console.log('A simple message'), env={}, sourceDescription=loggingInJS_simple.js, condition=null, label=null, optional=false)), logMessages=[A simple message], insight=Insight(message=, level=NONE))
``` 
This PR adds additional explicit logging:
```
20:08:50.314 [ INFO] maestro.orchestra.Orchestra.invoke: JsConsole: A simple message
```
Tested on Linux with https://github.com/Fishbowler/maestro-examples/tree/main/logging

Add console.log messages directly to the maestro log

---

maestro-studio/web/src/components/device-and-device-elements/BrowserActionBar.tsx

Prior to this fix it was white-on-white

Fix: dark mode for browser action bar

---

scripts/install.sh

Remove existing files from bin and lib as part of an upgrade/install
- Run locally over 1.39.9 (succeeded)
- Run locally over 1.39.9 with some extra and some renamed files (all gone)
- Run locally with no ~/.maestro directory (succeeded)

Safer install script

---

maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt
maestro-cli/src/main/java/maestro/cli/util/EnvUtils.kt
maestro-client/src/main/java/maestro/mockserver/MockInteractor.kt
maestro-studio/web/src/api/api.ts
maestro-studio/web/src/api/mocks.ts

Since Maestro Studio is now sunset, some commands no longer work and others are being migrated to [Robin](https://robintest.com).
This changes all the URLs to point to the new place
Notice "Ask AI" on Maestro Studio is currently broken - this points to the correct new api endpoint (which is not yet released)

stop using maestro cloud api

---

e2e/workspaces/demo_app/scrollUntilVisible_timeout.yaml

A timeout test story:
- Test used to take nearly 5s
- Test now takes about 6s
- Test wants to prove it's less than 20 seconds, so tested for 5.
- Now tests for 12.

fix: e2e race condition in scrollUntilVisible timeout test

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

feat: start trial option if not started

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt

Should also fix the same for `maestro record`
I've been able to test my fix using a little example flow: https://github.com/Fishbowler/maestro-examples/tree/main/env-vars
- With Maestro installed via curl -fsSL "https://get.maestro.mobile.dev/" | bash this works as is, using maestro test
- It doesn't work if I update run.sh to use maestro test -c
- My new Maestro branch works for both
#2310

Move env parsing and defaults to the runner to fix continuous

---

maestro-cli/src/main/java/maestro/cli/insights/TestAnalysisManager.kt

Adds extra validation to ignore analyze notifications on CI
Individuals reports that after uploading to the  cloud the output of the tests is not shown like before

fix(analyze): Ignore notification on CI

---

.github/workflows/test-e2e.yaml
maestro-ios-driver/src/main/kotlin/util/CommandLineUtils.kt
maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt
maestro-ios-driver/src/main/kotlin/util/XCRunnerCLIUtils.kt

This writes the log at the same place where we do for running driver with xcodebuild command.

fix: bring back logs with prebuilt mode

---

maestro-orchestra/src/main/java/maestro/orchestra/workspace/WorkspaceExecutionPlanner.kt

Fix globbing for flows via config on Windows
Tested on Windows 11 and macOS 15.3.1, running `maestro test someFolder` where someFolder contains a config, and the config has a valid flows key.
#2279

Fix system path separators for config globbing

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/StartDeviceCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt

Adding params to support picking OS and device model

device model + OS params on upload

---

CONTRIBUTING.md

I added a note in the contributing file about which version of Xcode is used when building the iOS XCTest runner app.
In the past I have run into issues where our CI build used an older version of Xcode (as is the case here) and contributors used a newer version and would inadvertently add changes that would build locally but not in CI.
This note makes contributors aware of this issue.
N/A
Hole in documentation.

Add note about Xcode version used in GitHub Action build step.

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/android/chromedevtools/DadbChromeDevToolsClient.kt
maestro-client/src/main/java/maestro/android/chromedevtools/DadbHttpClient.kt
maestro-client/src/main/java/maestro/android/chromedevtools/DadbWebSocketClient.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/resources/maestro-web.js
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Add an option to use Chrome dev tools to build the Android WebView hierarchy.
eg.
```
androidWebViewHierarchy: devtools
---
- launchApp
```
Also adds an option to studio CLI command to do the same:
```
maestro studio --android-webview-hierarchy=devtools
```

Add option to use Chrome dev tools for Android WebView hierarchy

---

maestro-cli/src/main/java/maestro/cli/util/FileUtils.kt

When running `maestro cloud` on a folder that contains non-flows (JS, Readme, config.yaml) the command would fail because every file was checked for isWebFlow(), and some can't be parsed as flows.
This would lead to this error:
```
Flow files must contain a config section and a commands section separated by "---". For example:
appId: com.example
---
- launchApp
The stack trace was:
maestro.orchestra.error.SyntaxError: Error reading ./parsing-arrays/config.yaml
Flow files must contain a config section and a commands section separated by "---". For example:
appId: com.example
---
- launchApp
at maestro.orchestra.yaml.YamlCommandReader.readConfigAndCommands(YamlCommandReader.kt:99)
at maestro.orchestra.yaml.YamlCommandReader.readConfig(YamlCommandReader.kt:60)
at …
```

Only check if flows are webflows

---

maestro
maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/CheckSyntaxCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/MaestroFlowParser.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
tmp.sh

✔️  Single command
```bash
$ echo "tapOn: foo" | maestro check-syntax -
OK
```
✔️  Full flow
```bash
$ cat << EOF  | maestro check-syntax -
---
- tapOn: foo
EOF
OK
```
✔️  List of commands
```bash
$ cat << EOF  | maestro check-syntax -
- tapOn: foo
- inputText: bar
EOF
OK
```
✔️  File input
```bash
$ maestro check-syntax MyFlow.yaml
OK
```
✔️  Errors
```bash
$ cat << EOF  | maestro check-syntax -
- tapOn: foo
- inp
EOF
/syntax-checker:2
╭────────────────────────────────────────────────────────────────────────────────╮
│ 1 | - tapOn: foo                                                               │
│ 2 | - inp                                                                      │
│          ^                                                                     │
│ …
```

Add maestro check-syntax command

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

this allows us to start supporting devices other than iphone 11 and more flexible runtime selection on Maestro Cloud

use device-model and device-os fields for ios

---

maestro-ai/src/main/java/maestro/ai/CloudPredictionAIEngine.kt
maestro-ai/src/main/java/maestro/ai/IAPredictionEngine.kt
maestro-cli/src/main/java/maestro/cli/auth/Auth.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Creating an interface for AIEnginePrediction. Using the CloudAIEnginePrediction implementation to call maestro's api to get the AI commands.
Pass the API Key from Run Tests - if present - to use in the API call
Tested running a workflow with AI commands both before and after the changes, with and without setting the MAESTRO_CLOUD_API_KEY, and passing the --api-key param.
Allow for maestro.dev to use the AI commands

maestro: making AI commands work

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/command/QueryCommand.kt
maestro-cli/src/main/java/maestro/cli/command/RecordCommand.kt
maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt

We introduced prebuilt mode on iOS to make driver setup faster and more consistent. While it's working as expected, it caused a regression in the Maestro Studio flow by sending the foreground app to the background.
This PR fixes that by:
1. **Avoiding backgrounding the app**: We switch back to using xcodebuild for flows where keeping the app in the foreground is necessary (e.g., Maestro Studio).
2. **Fixing infinite loop in device detection**: The recent changes for iOS physical device detection logic causes an infinite loop during local installation because user input isn't possible in the current setup. This PR disables that behavior in local mode.
Locally

fix: studio mode should not foreground running app

---

maestro

When multiple devices are connected and Maestro is run locally, the CLI prompts the user to select a device. However, because we were previously piping input into the CLI (echo "$input" | maestro ...), it disconnected the TTY, which prevented any interactive input.
Removed the echo pipe so that the TTY remains connected, allowing the CLI to properly prompt the user for input when needed.
Locally

fix: infinite loop on maestro studio

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/command/QueryCommand.kt
maestro-cli/src/main/java/maestro/cli/command/RecordCommand.kt
maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt

This PR switches setting up iOS driver with xcodebuild. 
The problem on cli using prebuilt mode is that it always put the running app in background. 
https://github.com/mobile-dev-inc/Maestro/issues/2456

fix: don't use prebuilt for cli on iOS 

---

maestro-client/src/main/java/maestro/device/DeviceService.kt
maestro-ios-driver/src/main/kotlin/util/IOSDevice.kt

Only filter connected devices. Since we observed not only connected but paired, unpaired and available are also visible on the devicectl list.

fix: only connected devices for iOS devices

---

maestro-ios-driver/src/main/kotlin/xcuitest/installer/IOSBuildProductsExtractor.kt

When running the CLI with sharding > 1, this function can be executed by multiple threads concurrently. This leads to a race condition where multiple threads attempt to create the same file system for a given URI, resulting in a `FileSystemAlreadyExistsException`.
This PR adds logic to safely handle this case by attempting newFileSystem, and falling back to getFileSystem if it already exists ensuring the file system is reused instead of causing the thread to fail.
https://github.com/mobile-dev-inc/Maestro/issues/2464

fix: sharding on iOS

---

maestro-client/src/main/java/maestro/device/DeviceService.kt
maestro-ios-driver/src/main/kotlin/util/IOSDevice.kt
maestro-ios-driver/src/test/kotlin/DeviceCtlResponseTest.kt

Made os version number and name in device properties nullable. We got 2 reports where we got to know that we might not have name and os number.
Updated the unit tests as well.

[MAE 167] breaking deserialization

---

maestro-client/src/main/java/maestro/device/DeviceService.kt
maestro-ios-driver/src/main/kotlin/util/IOSDevice.kt
maestro-ios-driver/src/main/kotlin/util/LocalIOSDevice.kt
maestro-ios-driver/src/test/kotlin/DeviceCtlResponseTest.kt

Hardware udid which is later used as destination id in xcodebuild commands in case of physical devices, could be missing. This PR handles that case on new model we added.

fix: hardware udid can be missing

---

maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-client/src/main/java/maestro/Errors.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt

1. Introduce a debug info on maestro errors to send debug messages on failures. This is to help users guide how they show be changing commands if something errors out on assertions specifically scrollUntilVisible.
2. scrollUntilVisible command also doesn't show other attributes like speed, timeout which are even there by default. This PR includes them in description

[MA 3258] Introducing debug info on element not found exceptions

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/120_tap_on_element_retryTapIfNoChange.yaml

**WARNING:** This is a breaking change for flows that are benefitting from the previous default behavior of retrying taps when Maestro determines the UI has not changed.
It's very difficult to know whether the previous behavior was actually benefitting anyone, but there are certainly lots of complaints of the default behavior causing problems.
I propose ripping the bandaid off with this PR and changing this behavior to an opt-in.
Resolves #1202

Do no retry taps by default

---

maestro-client/src/main/java/maestro/ViewHierarchy.kt
maestro-client/src/main/java/maestro/drivers/WebDriver.kt
maestro-client/src/main/resources/maestro-web.js

`<select>` tags are handled differently than every other DOM element. For one - options are not rendered as part of the DOM but rather by the browser itself, so we do not get any `bounds` back.
To work around that, we pretend that there are visible `option` elements on the screen, just very far away (in what I call a "synthethic coordinate space"). If such element is clicked, we detect it and handle tap ourselves (without Selenium). That allows to keep the rest of the Maestro implementation untouched.

[Web] Adding support for <select> tag

---

gradle/libs.versions.toml
maestro-cli/build.gradle.kts
maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/analytics/Analytics.kt
maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt

users can now opt-out any time by setting the `MAESTRO_CLI_NO_ANALYTICS` env variable (works on CI and local devices)

save anonymous analytics to posthog.

---

maestro-cli/src/main/java/maestro/cli/driver/DriverBuilder.kt

Instead of the hardocded `process.waitFor(120, TimeUnit.SECONDS)` we propose a way to set this with an environment variable (`MAESTRO_XCODEBUILD_WAIT_TIME`), which could help on slower host machines.

DriverBuilder: make the xcodebuild timeout configurable

---

gradle/libs.versions.toml
maestro-cli/build.gradle.kts
maestro-cli/src/main/java/maestro/cli/mcp/MaestroTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/McpServer.kt
maestro-cli/src/main/java/maestro/cli/mcp/schema/McpSchemaBase.kt
maestro-cli/src/main/java/maestro/cli/mcp/schema/SchemaValidator.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/BackTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/CheatSheetTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/CheckFlowSyntaxTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/InputTextTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/InspectViewHierarchyTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/LaunchAppTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/ListDevicesTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/QueryDocsTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/RunFlowFilesTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/RunFlowTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/StartDeviceTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/StopAppTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/TakeScreenshotTool.kt
maestro-cli/src/main/java/maestro/cli/mcp/tools/TapOnTool.kt
maestro-cli/src/test/mcp/tool-tests-with-device.yaml
maestro-cli/src/test/mcp/tool-tests-without-device.yaml

Upgrades the MCP tools implementation to use a schema-driven architecture with automatic JSON schema generation and runtime validation. This refactoring improves type safety, reduces boilerplate code, and ensures MCP protocol compliance through automated schema generation using the xemantic-ai-tool-schema library.
None - The MCP protocol interface remains unchanged. This is an internal refactoring that maintains the same external API.

refactor: Upgrade MCP tools to schema-driven architecture with automatic validation

---

maestro-client/src/main/java/maestro/js/GraalJsEngine.kt
maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-client/src/main/java/maestro/js/RhinoJsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/GraalJsEngineTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/kotlin/maestro/test/RhinoJsEngineTest.kt
maestro-test/src/test/resources/127_env_vars_isolation_graaljs.yaml
maestro-test/src/test/resources/127_env_vars_isolation_rhinojs.yaml

Environment variables from one runFlow command were persisting and being accessible to subsequent peer runFlow commands, violating expected scoping rules. This change ensures proper isolation while maintaining inheritance from parent flows to subflows.
Implementation:
- Add enterEnvScope/leaveEnvScope methods to JsEngine interface
- RhinoJS: leverage existing JavaScript scope mechanism
- GraalJS: implement manual stack-based environment management
- Orchestra: wrap runSubFlow execution with env scoping
Testing:
- Added a flow test for both graal and rhino engines to confirm the behavior works as expected (see the two yaml files; they demonstrate it clearly. Thanks to @Fishbowler for a good example repro in the ticket!)
- Added simple unit tests for the new behavior in the two engine …

feat: isolate environment variables between peer runFlow commands

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/test/java/maestro/orchestra/CommandDescriptionTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/077_env_special_characters.yaml
maestro-test/src/test/resources/127_env_vars_isolation_rhinojs.yaml

Graal is now the default engine, but we allow rhino if specified via `jsEngine: rhino` in the test config.
There are subtle differences in the Graal implementation that _could_ affect users in edge case situations. Here are the ones I discovered while updating the tests:
- correctly resolves `${parseInt(3)}` to `3` (rhino would resolve to `3.0`)
- preserves newlines in ENV vars passed in via CLI or YAML (rhino would strip those out)
- correctly escapes double slashes (rhino would run two passes of escaping, reducing `////` to `/`)
- ran all tests including with `./gradlew build`
- did not run e2e tests (assuming CI will do that)
MA-3547
https://github.com/mobile-dev-inc/maestro/issues/2049

MA-3547 Make Graal default JS engine

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt

Fixed issues with web flow test related to this [PR](https://github.com/mobile-dev-inc/Maestro/commit/be97bc657a671577de110c8ee77cd4ad71989f1a) which cause some issues with `test` and `sharding`.
**Issue 1:**
No web flow in config, yet it stills open the web flow. Reason was we were checking all the files and if any of them included web flow we were adding that device. 
https://github.com/user-attachments/assets/c1a2a36a-2626-44de-99ec-4cc63a29414d
**Fix: Updated the function to check files that need to be executed.**
**Issue 2:**
Opened android and tried to do sharding between 2 devices. Workspace has both android and web flows. But it errors out saying only one device present. 
https://github.com/user-attachments/assets/ced42a6d-d690-4eba-8af9-a9bc9f7c7657
**Fix: In case web flow is …

fix: web flow check & mix sharding

---

maestro-cli/src/main/java/maestro/cli/report/TestDebugReporter.kt
maestro-cli/src/test/kotlin/maestro/cli/report/TestDebugReporterTest.kt

Fix a long-standing issue where the log cleanup has been broken, and accumulating cruft on disk.
https://maestro--dev.slack.com/archives/C041FU72T54/p1750333850096709
Manually tested on a Mac. Added a test.
?? How can I not find this in the tracker ??

Fix cleanup of logs older than 14 days

---

maestro-cli/src/main/java/maestro/cli/util/DependencyResolver.kt
maestro-cli/src/main/java/maestro/cli/util/WorkspaceUtils.kt
maestro-cli/src/test/kotlin/maestro/cli/util/DependencyResolverTest.kt

**Enhance Cloud Upload with Automatic Dependency Discovery**
When uploading a single flow file to Maestro Cloud, the system now automatically discovers and includes all dependent files (subflows, scripts, and media) in the workspace ZIP. This eliminates the need for users to upload the workspace in order to run one flow that needs other files.
- **New `DependencyResolver` class**: Automatically discovers dependencies by parsing flow files for `runFlow`, `runScript`, and `addMedia` commands
- **Enhanced `WorkspaceUtils`**: Automatically detects single file uploads and includes dependencies, while maintaining existing directory upload behavior
- **Before**: Users had to upload workspace in order to run one specific file with dependencies
- **After**: Users can upload a single flow file and …

[MA-3571] Cloud Upload Resolve Dependencies for Single Flow Upload

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/model/RunningFlow.kt

With recent changes that have been deployed to maestro server, this PR allows accurate reporting of `time` values which are used in generated JUnit reports. Rather than inaccurately calculating the durations on client side (i.e. maestro-cli) we instead get the durations from the flow status on the server.
PR also fixes a bug where its possible that the time duration would incorrectly be zero. This would happen in the case where the poll duration is longer than flow status changes from the server, causing the currently existing logic to fail as it relies on detecting a state transition to `RUNNING` in order to calculate the durations.
There is an additional change to be wary of, previously if the duration field was `null` then this would get reported in JUnit as `time="0"`. Now the `time` …

feat: Accurately use durations from server

---

maestro-cli/src/main/java/maestro/cli/report/HtmlTestSuiteReporter.kt
maestro-cli/src/main/java/maestro/cli/report/JUnitTestSuiteReporter.kt
maestro-cli/src/main/java/maestro/cli/report/TestSuiteReporter.kt

Adds the start time to HTML generate test report
There aren't any existing tests however this is what the result looks like locally
Resolves: https://github.com/mobile-dev-inc/Maestro/issues/2554

feat: Add start time to HTML report

---

maestro-cli/src/main/java/maestro/cli/report/TestDebugReporter.kt

Fix `--test-output-dir` parameter causing FileNotFoundException by ensuring proper directory creation. 
The issue was that `updateTestOutputDir()` was setting `debugOutputPath` directly to the user-provided directory without creating it, bypassing the directory creation logic in `getDebugOutputPath()`. This fix resets `debugOutputPath` to `null`, forcing the proper initialization flow that creates the directory structure.
Tested with:
```bash
./maestro test flow.yaml --test-output-dir=./test_output
```
Before: `FileNotFoundException: /test_output/commands-(...).json (No such file or directory)`
After: Successfully creates directory and writes test artifacts
Fixes FileNotFoundException when using `--test-output-dir` parameter due to missing directory creation.

[MA-3574] Argument --test-output-dir fix for when directory not existent

---

.github/workflows/ios-integration-tests.yaml
.github/workflows/test-e2e.yaml
e2e/download_apps

* Update download_apps to take an optional case insensitive parameter to specify platform.
* When platform is specified, skip apps belonging to other platforms
* When no platform is specified, download everything
* Update CI to use the parameter in the relevant places
This will save ~5 seconds on every run. You're welcome.
```
./download_apps
./download_apps ios
./download_apps android
./download_apps iOS
./download_apps Android
```

Only download apps as needed in CI

---

maestro-cli/build.gradle.kts

This PR fixes jreleaser not producing the minimum JVM version check. This minimum JVM version check was introduced at https://github.com/mobile-dev-inc/homebrew-tap/pull/7 but it would get overridden every single time a new jreleaser release is made
To test this locally do
```
export JRELEASER_GITHUB_TOKEN=not used
./gradlew :maestro-cli:jreleaserPrepare --no-daemon --no-parallel
```
Then go into `/maestro-cli/build/jreleaser/prepare/maestro/brew/Formula` and you can see the generated ruby formula, on my system its
```ruby
class Maestro < Formula
desc "The easiest way to automate UI testing for your mobile app"
homepage "https://maestro.mobile.dev"
url "https://github.com/mobile-dev-inc/maestro/releases/download/cli-2.0.1/maestro.zip"
version "2.0.1"
sha256 …
```

Fix jreleaser minimum jvm version homebrew

---

maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-cli/src/test/kotlin/maestro/cli/command/TestCommandTest.kt
maestro-cli/src/test/resources/workspaces/test_command_test/00_mixed_web_mobile_flow_tests/mobileflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/00_mixed_web_mobile_flow_tests/mobileflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/00_mixed_web_mobile_flow_tests/webflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/00_mixed_web_mobile_flow_tests/webflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/01_web_only/webflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/01_web_only/webflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/02_mobile_only/mobileflow1.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/02_mobile_only/mobileflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/03_mixed_with_config_execution_order/config.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/03_mixed_with_config_execution_order/subFolder/mobileflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/03_mixed_with_config_execution_order/subFolder/mobileflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/03_mixed_with_config_execution_order/subFolder/webflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/03_mixed_with_config_execution_order/subFolder/webflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/04_web_only_with_config_execution_order/config.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/04_web_only_with_config_execution_order/subFolder/mobileflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/04_web_only_with_config_execution_order/subFolder/mobileflow2.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/04_web_only_with_config_execution_order/subFolder/webflow.yaml
maestro-cli/src/test/resources/workspaces/test_command_test/04_web_only_with_config_execution_order/subFolder/webflow2.yaml

In case the `executionOrder` was there and it has wrong name, that means `flows` are `0`. Which caused `allFlowsAreWebFlow` to give true.
Added the check for empty flows as well as included the sequenceFlow as well.
Fixes #2674

fix: condition for checking web flows in case flows length is zero

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt
maestro-cli/src/test/kotlin/maestro/cli/cloud/CloudInteractorTest.kt

All the Runs output was removed from the cli cloud upload after this [Pull Request](https://github.com/mobile-dev-inc/Maestro/pull/2652)
Added back the Runs output logs and used terminalStatus array to detect the end state of run

fix: added back runs to cli cloud upload output

---

maestro-cli/src/main/java/maestro/cli/model/TestExecutionSummary.kt
maestro-cli/src/main/java/maestro/cli/report/HtmlTestSuiteReporter.kt
maestro-cli/src/main/java/maestro/cli/report/JUnitTestSuiteReporter.kt
maestro-cli/src/test/kotlin/maestro/cli/report/HtmlTestSuiteReporterTest.kt
maestro-cli/src/test/kotlin/maestro/cli/report/JUnitTestSuiteReporterTest.kt
maestro-cli/src/test/kotlin/maestro/cli/report/TestSuiteReporterTest.kt

This PR fixes incorrect reporting of failures in `HtmlTestSuiteReporter`. The error appeared to be a simple one, due to the logic of calculating failures there was double counting of test failures. The logic of `getFailedTests` was simplified to just use a basic filter.
`failures` was also moved to a common function so that we don't get divergence in what constitutes a failure. Note that there are some other data structures which also represent test reports but that should be fixed in a future PR as its out of scope.
Common testing logic was moved out of `JUnitTestSuiteReporterTest` into a `TestSuiteReporterTest` so that we could add newly added tests to `HtmlTestSuiteReporterTest` in order to verify that the failure count is working (amongst other things).
Resolves: …

fix: Failed test reporting in HtmlTestSuiteReporter

---

maestro-client/src/main/java/maestro/device/DeviceError.kt
maestro-client/src/main/java/maestro/device/DeviceService.kt

This should better help in debugging as it puts the last exception in the `DeviceError` exception allowing the cause to be shown properly

chore: Put last error in device exception

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

This can better help in diagnosing AndroidDriver issues as well as being able to catch `StatusRuntimeException` as a root cause

chore: Put root cause in MaestroException.DriverTimeout

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

We should log these as warn instead of errors to reduce log error pollution since this is a client/user problem

chore: Log MaestroException.ElementNotFound as a warn

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

* abruptClose = true short-circuited close(), returning on the first line.
* This prevented tcp forwarder threads and other resources (instrumentation session, etc.) from being released.
* In production pods we observed:
* Pods failing to shut down cleanly because the forwarder thread was still alive. 
* lingering threads trying to make connection with dadb. The first evidence is in the stacktrace itself that has thread name:
```
Exception in thread "pool-117-thread-7" java.net.SocketTimeoutException: Connect timed out                                                                                                                        │
│     at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) …
```

fix: simplify cleanup because it leads leaking resources

---

maestro-android/src/androidTest/java/dev/mobile/maestro/MaestroDriverService.kt

Self-evident 1 character change to fix a problem where we're always deleting 1 character extra. Background in the linked issue.
```
- inputText: 'testing'
- assertVisible: 'testing'
- eraseText: '3'
- assertNotVisible: 'testing'
- assertVisible: 'test'
```
#2122

Fix off-by-one when specifying count with eraseText

---

maestro-cli/src/main/java/maestro/cli/App.kt

If you run maestro with empty cli args it crashes at this point since `args[0]` is not set
Resolves https://github.com/mobile-dev-inc/Maestro/issues/2726?

fix: Fix crash on empty args
