.github/workflows/publish-release.yml
build.gradle.kts
gradle.properties

- Also changes version to 1.0.0

Adds action to publish on maven central

---

maestro-client/src/main/java/maestro/Errors.kt

Making ElementNotFound.hierarchyRoot field public

---

maestro-cli/src/main/java/maestro/cli/runner/CliWatcher.kt
maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/ResultView.kt
maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/android/AndroidAppFiles.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroConfig.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

Also adds a nice convenience for restarting a test in continuous mode by pressing ENTER.

Proper initFlow state restoration

---

maestro-cli/src/main/java/maestro/cli/util/MaestroFactory.kt

This aligns better with the logic that was in v1.2.3

Improve logic for autoselecting platform

---

maestro-client/src/main/java/maestro/Errors.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/MaestroTimer.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/026_assert_not_visible.yaml

assertNotVisible command

---

RELEASING.md

Script most of the steps to reduce mental load during release cycles

Update release procedure

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/029_long_press_on_element.yaml
maestro-test/src/test/resources/030_long_press_on_point.yaml

Feture: long press

---

maestro-client/src/main/java/maestro/utils/ViewUtils.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/035_refresh_position_ignore_duplicates.yaml

Fix: refreshElement was sometimes matching a wrong view

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/ViewHierarchy.kt
maestro-client/src/main/java/maestro/utils/ViewHierarchy.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

This PR doesn't have a dependency on 150.

Replace `ViewUtils` with a `ViewHierarchy` value class

---

maestro-client/build.gradle
maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Errors.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/build.gradle
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlTakeScreenshot.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/041_take_screenshot.yaml

Credit for scaffolding and Android implementation goes to @ragunathjawahar 
Original proposal: #187

Support screenshots

---

CHANGELOG.md

Reverse the order of releases in CHANGELOG.md to show newest first

---

.gitignore
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/028_env.yaml

Tweak: allow env variables in LaunchAppCommand appId

---

maestro-cli/src/main/java/maestro/cli/runner/CliWatcher.kt
maestro-cli/src/main/java/maestro/cli/runner/FileWatcher.kt
maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlConfig.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlRunFlow.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/046_run_flow.yaml
maestro-test/src/test/resources/047_run_flow_nested.yaml

```
---
- launchApp
```
```
---
- runFlow: flowA.yaml
- tapOn: button
```

Run flow implementation

---

.github/PULL_REQUEST_TEMPLATE.md
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Enter character by character instead of the whole text which sometimes is leading to missing characters.
Reproduced by manually creating commands from one of the apps facing issue flows in Kotlin. 
https://github.com/mobile-dev-inc/maestro/issues/207

Input character by character to ensure everything is entered

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

In rare cases where `AndroidDriver` is not closed properly after being used, Maestro becomes unoperational as the port remains in use. This change closes the port if it already allocated and is not released. Furthermore, we print a warning message whenever such situation occurs.
Tested by creating multiple Maestro instances in a dummy `main()` function

Fix: close TCP forwarder if it is already in use

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Increase the input speed, by the input of multiple characters at once. Right now 3
Tested in 10 iterations with 3 chunked characters as input. 
https://github.com/mobile-dev-inc/maestro/issues/222

Input characters in chunked way

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSetLocation.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/051_set_location.yaml

Add support to set location on iOS.
- Integration tests to test commands and driver integration.
- @amanjeetsingh150 is helping with testing this on iOS until we setup iOS dev environment on my machine this week.
This PR addresses #105.

feat: set geolocation support (iOS only, pending manual testing)

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

fix `clipboardPaste` on ios
reference: https://developer.apple.com/documentation/uikit/uikeyboardhidusage/keyboardpaste

fix clipboardPaste on ios

---

maestro-cli/build.gradle
maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/DownloadSamplesCommand.kt
maestro-cli/src/main/java/maestro/cli/util/FileDownloader.kt

Usage: `maestro download-samples`
Archive: https://storage.googleapis.com/mobile.dev/samples/samples.zip

Download Samples command

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt
maestro-cli/src/main/java/maestro/cli/util/FileUtils.kt

Also fixing some minor leaks in `ApiClient` along the way

Feature: zip iOS apps before sending them for upload

---

maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/056_ignore_error.yaml

In certain environments we would like to allow custom error resolution (i.e. `takeScreenshot` command does not work on a certain machine).
Integration tests. No changes affecting CLI tool.

Tweak: Orchestra cutomisable error resolution

---

maestro-client/src/main/java/maestro/android/AndroidAppFiles.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Using the `ManifestData.launcherActivity` to run the app. I think it should fix #279

Fix #279 opening leak canary instead of app launcher

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

maestro currently matches every available simulator device model with every runtime that supports running on that device.
If multiple runtimes support the same device, device selection will show the device duplicated:
This PR changes that behaviour and only lists devices that the user (or Xcode when Xcode installed) has configured:
Note: Press cmd+shift+2 to configure simulators in Xcode.
Tested locally

Only list existing iOS Simulator devices

---

maestro-client/src/main/java/maestro/android/AndroidExt.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Checking error output and fallback to a monkey in case the start activity fails
Tested on client app

Fix monkey fall back in launching apps

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/BugReportCommand.kt
maestro-cli/src/main/java/maestro/cli/debuglog/DebugLogStore.kt

Add `maestro bugreport` to print out the link to GitHub and the location of log files.

Add `maestro bugreport` command

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt

This PR updates `ApiClient.upload` to automatically retry upload requests up to 3 times when a 5XX is returned back from the Maestro Cloud API.

Retry upload request up to 3 times on 5XX

---

maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Condition.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/util/Env.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCondition.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/065_subflow.yaml
maestro-test/src/test/resources/065_when_true.yaml

Add a new condition that only runs a flow if the condition is JS-truthy (not null, not empty, non 0, not false):
```
- runFlow:
when:
true: ${1 + 1}
file: subflow.yaml
```

Feature: when true

---

maestro-cli/src/main/java/maestro/cli/command/BugReportCommand.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/DownloadSamplesCommand.kt
maestro-cli/src/main/java/maestro/cli/command/LoginCommand.kt
maestro-cli/src/main/java/maestro/cli/command/LogoutCommand.kt
maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/command/QueryCommand.kt
maestro-cli/src/main/java/maestro/cli/command/RecordCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt

Add descriptions to cli commands

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/view/ViewUtils.kt
maestro-studio/server/src/main/java/maestro/studio/MaestroStudio.kt
maestro-studio/web/src/App.tsx
maestro-studio/web/src/index.css

Note: Studio is a WIP
https://user-images.githubusercontent.com/847683/205921802-d34d8025-5b96-4d4a-a6ae-1c51cd619126.mov

Studio: Show screenshot alongside hierarchy

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/MaestroCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandSerializationTest.kt

I ran a local build on my other OSS project. I enabled `Pointer location` from Developer Options (Android) for testing to be easy.
```yaml
- launchApp
- tapOn:
point: 100,100
- tapOn:
point: 10%,70%
```
#363

[Feature] - Tap with percents

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-studio/web/src/Examples.tsx

* Remove icon from Mac dock
* Prefer port 9999
* Add instructions on how to stop Maestro Studio
* Fix Conditional code snippet

Maestro fixes

---

.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml
maestro-cli/build.gradle
maestro-cli/src/main/java/maestro/cli/command/network/SetupForProxyCommand.kt
maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-client/build.gradle
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-ios/build.gradle
maestro-ios/src/main/java/ios/xcrun/CommandLineUtils.kt
maestro-ios/src/main/java/ios/xcrun/Simctl.kt
maestro-ios/src/main/java/ios/xcrun/SimctlList.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/build.gradle
maestro-test/src/main/kotlin/maestro/test/drivers/FakeTimer.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-utils/build.gradle
maestro-utils/gradle.properties
maestro-utils/src/main/kotlin/MaestroTimer.kt
settings.gradle.kts

Move Simctl to the maestro-ios package so that the maestro driver can call out to simctl.
Build locally

Move Simctl to iOS package

---

maestro-orchestra-models/src/main/java/maestro/orchestra/util/InputRandomTextHelper.kt

fix: missing letter `Y` and `j`

fix: missing letter

---

maestro-client/src/main/java/maestro/drivers/XcUITestDriver.kt

When setting up the XCTest server, wait until we can connect to the server before proceeding.

Fix iOS XCTest server race condition

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Adds placeholder values of xcuielement if value is empty

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Tweaking the start and end points for the swipe command.
@Leland-Takamine @dmitry-zaitsev 
Performed swipe command on both Android and iOS applications.

Tweak Swipe Command Start/End Points

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-studio/web/src/AnnotatedScreenshot.tsx
maestro-studio/web/src/Inspect.tsx
maestro-studio/web/src/InteractPage.tsx
maestro-studio/web/src/InteractableDevice.tsx
maestro-studio/web/src/Modal.tsx
maestro-studio/web/src/ReplView.tsx
maestro-studio/web/src/SaveFlowModal.tsx

Styling updates:
Add right click to inspect elements in interact page:

Maestro Studio: Interact Mode - Add inspect modal

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt

Also catching exceptions during heartbeat just in case

Tweak: added logging to session heartbeat and decreased interval

---

maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlRepeatCommand.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/075_repeat_while.yaml

Re-introducing repeat-while command

Feature: repeat while

---

maestro-studio/server/src/main/java/maestro/studio/DeviceScreenService.kt
maestro-studio/web/src/InteractableDevice.tsx

Update Maestro Studio logic to ensure that filtering logic is consistent with Orchestra. This inconsistency was causing incorrect indexes to be suggested in Maestro Studio.

Fix Maestro Studio Indexes

---

samples/android-advanced-flow.yaml
samples/ios-advanced-flow.yaml
samples/scripts/getSearchQuery.js
samples/subflows/onboarding-android.yaml
samples/subflows/onboarding-ios.yaml

Adds two new advanced flows (one for iOS and one for Android) that incorporates swiping, subflows and javascript as well as assertions and input text.

Add more advanced flows to samples

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/076_optional_assertion.yaml

Optional assertions will be skipped in case when they are failing

Tweak: assert command now respects optional flag

---

maestro-client/build.gradle
maestro-client/src/main/java/maestro/js/Js.kt
maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/077_env_special_characters.yaml

Fix: more forgiving Js sanitization

---

maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-cli/src/main/java/maestro/cli/util/WorkspaceUtils.kt
maestro-cli/src/test/kotlin/maestro/cli/util/WorkspaceUtilsTest.kt
maestro-cli/src/test/resources/tags/config.yml

Additionally, we were not sending `config.yaml` to backend.
cc @felipevolpone

Fix: local test suite included non-flow files

---

maestro-cli/src/main/java/maestro/cli/view/ProgressBar.kt

Manual
Fixes progressbar crash when progress value is negative (500 error) and ANSI is disabled.

Progressbar fix when value negative

---

maestro-client/src/main/java/maestro/Point.kt
maestro-client/src/test/java/maestro/PointTest.kt

Fix: fix Point JSON serialization

---

maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

* Log the response body if hierarchy request fails

Log the response body if request fails

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt

Integration
ScrollUntilVisible: Adds JS script support in ScrollUntilVisible element selector

Fix: JS script support in ScrollUntilVisible element selector

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Seems some PRs changes overlapped and broke something
Reference error

Fixes reference error

---

maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerInitCommand.kt
maestro-cli/src/main/java/maestro/cli/command/mockserver/MockServerOpenCommand.kt
maestro-studio/server/src/main/java/maestro/studio/MockInteractor.kt
maestro-studio/web/src/MockPage.tsx
maestro-studio/web/src/MockServerInstructions.tsx
maestro-studio/web/src/mocks.ts

- More user friendly error messages 
- UI fixes in Mock Server UI
- Don't deploy workspace when running `maestro mockserver init`

Minor tweaks in Moock Server

---

maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

Remove dependency from IOSDevice to IDB
Not tested, no logic changed

Remove dependency from IOSDevice to IDB

---

maestro-driver-ios/maestro-driver-iosUITests/Routes/Handlers/InputTextRouteHandler.swift

Remove the XCUIElement based text input variant because it crashes with apps with big view hierarchies (react native).
Manual

Solve an issue where Element selector crashes the XCTestRunner

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Use XCTest for launching app on iOS

Use xcrun for launching app on iOS

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Use XCTest for opening URL on iOS

Use xcrun for opening URL on iOS

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Use XCTest for setting location in iOS
Tested locally

Use xcrun for setting location in iOS

---

maestro-studio/web/src/ConfirmationDialog.stories.tsx
maestro-studio/web/src/ConfirmationDialog.tsx
maestro-studio/web/src/ReplView.tsx

Show a confirmation dialog before deleting commands when more than one command is selected to be deleted, to ensure users don't accidentally remove commands.
https://user-images.githubusercontent.com/6113675/218087591-f687e49e-5380-49c7-b7db-49253a7b8e5a.mov
Tested locally, see attached screen recording.

Ask for confirmation before deleting more than one command

---

maestro-cli/src/main/java/maestro/cli/util/WorkspaceExecutionPlanner.kt
maestro-cli/src/test/kotlin/maestro/cli/util/WorkspaceExecutionPlannerTest.kt
maestro-cli/src/test/resources/workspaces/010_global_include_tags/config.yaml
maestro-cli/src/test/resources/workspaces/010_global_include_tags/flowA.yaml
maestro-cli/src/test/resources/workspaces/010_global_include_tags/flowA_subflow.yaml
maestro-cli/src/test/resources/workspaces/010_global_include_tags/flowB.yaml
maestro-cli/src/test/resources/workspaces/010_global_include_tags/flowC.yaml
maestro-cli/src/test/resources/workspaces/010_global_include_tags/flowD.yaml
maestro-cli/src/test/resources/workspaces/010_global_include_tags/flowE.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/config.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/flowA.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/flowA_subflow.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/flowB.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/flowC.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/flowD.yaml
maestro-cli/src/test/resources/workspaces/011_global_exclude_tags/flowE.yaml
maestro-orchestra-models/src/main/java/maestro/orchestra/WorkspaceConfig.kt

Test tags give you further flexibility to customize which Flows are executed in a test suite. This can also be configured in the config.yaml file:
```
includeTags:
- onboarding
excludeTags:
- subflow
```

Feature: global tags

---

maestro-client/src/main/java/maestro/Filters.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/ElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlElementSelector.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeLayoutElement.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/083_assert_properties.yaml

Allow assertion on properties:
- `selected`
- `checked`
- `focused`
Solves #313

Feature: assertion on properties

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Use xcrun for uninstall

---

maestro-studio/web/src/InteractPage.tsx

Fix error presentation in Interact page

---

samples/subflows/onboarding-ios.yaml

Remove the extra swipe on `samples/ios-advanced-flow.yaml`

Swipe three times for Wikipedia example iOS

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Wait for app to settle after xctest launch app

Wait for app to settle after xctest launch app

---

maestro-studio/web/src/ConfirmationDialog.stories.tsx
maestro-studio/web/src/ConfirmationDialog.tsx
maestro-studio/web/src/ReplView.tsx

- Update title for confirmation dialog to show number of commands to delete
- Require confirmation before deleting one command as well
https://user-images.githubusercontent.com/6113675/218737010-74444d36-055f-4781-a753-84c21069a1de.mov
Tested locally, see demo video.

UX tweaks for delete commands confirmation

---

maestro-studio/web/src/ActionModal.tsx
maestro-studio/web/src/App.stories.tsx
maestro-studio/web/src/Banner.tsx
maestro-studio/web/src/DeprecatedInspectPage.stories.tsx
maestro-studio/web/src/DeprecatedInspectPage.tsx
maestro-studio/web/src/ElementSearch.tsx
maestro-studio/web/src/Examples.tsx
maestro-studio/web/src/Inspect.tsx
maestro-studio/web/src/InteractPage.tsx
maestro-studio/web/src/MockPage.tsx
maestro-studio/web/src/MockServerInstructions.tsx
maestro-studio/web/src/PageSwitcher.tsx
maestro-studio/web/src/ReplView.tsx
maestro-studio/web/src/SaveFlowModal.tsx
maestro-studio/web/src/theme.tsx
maestro-studio/web/tailwind.config.js

- Add support for dark mode, that supports both system preference and manual selection
- Add a theme toggle button to all pages
**Demo**
https://user-images.githubusercontent.com/6113675/218985463-247b9767-2931-4580-899d-2265d7dad5ec.mov
**Mock page**
**Deprecated inspect page**
Tested locally, see demo and attached pictures.

Introduce dark mode to Studio

---

maestro-studio/web/src/ConfirmationDialog.tsx
maestro-studio/web/src/InteractPage.tsx

- Add better dark mode support to confirmation dialog
- Fix resolution bug of Interact page in Safari
Fixes #809

Various UI tweaks

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt

Use XCTest for tapping on iOS

---

maestro-studio/web/.storybook/main.js
maestro-studio/web/.storybook/preview.js
maestro-studio/web/package-lock.json
maestro-studio/web/package.json
maestro-studio/web/src/App.tsx
maestro-studio/web/src/DeprecatedInspectPage.tsx
maestro-studio/web/src/ElementSearch.tsx
maestro-studio/web/src/Header.stories.tsx
maestro-studio/web/src/Header.tsx
maestro-studio/web/src/Inspect.stories.tsx
maestro-studio/web/src/Inspect.tsx
maestro-studio/web/src/InteractPage.tsx
maestro-studio/web/src/InteractableDevice.tsx
maestro-studio/web/src/MockPage.tsx
maestro-studio/web/src/MockServerInstructions.tsx
maestro-studio/web/src/index.tsx
maestro-studio/web/src/mocks.ts

- Add a `Header` component containing a title and the `ThemeToggle`
- Fix a layout issue for Interact page in Firefox
- Add react router dependency
**Interact page with Header component**
| Before  | After |
| ------------- | ------------- |
|  <img width="1728" alt="before" src="https://user-images.githubusercontent.com/6113675/220393382-e45302c1-c13d-458a-8a8d-1921090143f2.png"> | <img width="1728" alt="after" src="https://user-images.githubusercontent.com/6113675/220393468-4d7c91a9-efcb-428e-b1a0-05274a29b6d8.png"> |
Tested locally and in Storybook.

Add Header component to Studio; Fix Firefox layout bug

---

maestro-driver-ios/build-maestro-ios-runner.sh

Exit xctest runner app build script on error

Exit on compilation error

---

maestro-studio/web/src/ReplView.tsx

- Add proper dark mode support for play icon in `ReplView`

Add dark mode support for PlayButton in ReplView

---

maestro-xcuitest-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

Refactor in XCTestDriverClient to simplify json requests and reduce repetition.

Simplify making json calls from XCTestDriverClient

---

maestro-xcuitest-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

Add USE_XCODE_TEST_RUNNER flag for running the xctest runner from Xcode.
This allows for easier research and development on the xctest runner.

Add flag USE_XCODE_TEST_RUNNER to allow running the xctest runner from Xcode

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

- Adds a check for extracting APK name and don't fail if we are not able extract APK name
- Wait until screen is static before autoVerification

Adds a check for extracting APK name

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/util/EnvUtils.kt

Read API key from `MAESTRO_CLOUD_API_KEY` instead of `MDEV_API_KEY`.

Update api key env var name

---

samples/wikipedia-android-advanced/auth/login.yml
samples/wikipedia-android-advanced/auth/signup.yml
samples/wikipedia-android-advanced/dashboard/copy-paste.yml
samples/wikipedia-android-advanced/dashboard/feed.yml
samples/wikipedia-android-advanced/dashboard/main.yml
samples/wikipedia-android-advanced/dashboard/saved.yml
samples/wikipedia-android-advanced/dashboard/search.yml
samples/wikipedia-android-advanced/onboarding/add-language.yml
samples/wikipedia-android-advanced/onboarding/main.yml
samples/wikipedia-android-advanced/onboarding/remove-language.yml
samples/wikipedia-android-advanced/run-test.yml
samples/wikipedia-android-advanced/scripts/fetchTestUser.js
samples/wikipedia-android-advanced/scripts/generateCredentials.js

Updates with advanced wikipedia samples

Adds wikipedia samples

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-xcuitest-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

No functional or nonfunctional change

Minor cleanups

---

maestro-cli/src/main/java/maestro/cli/idb/IdbCompanion.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-client/src/main/java/maestro/LocalIdbRunner.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbRunner.kt

No functional change
Test suite plus manual tests

Add IdbRunner class to start and stop idb

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Implement the install() command using xctest
Tested by calling the install command manually from inside maestro (the command is currently not available in maestro)

Implement install() using simctl

---

MaestroSDK.podspec
maestro-sdk/ios/Maestro SDK.xcworkspace/contents.xcworkspacedata
maestro-sdk/ios/Maestro SDK.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
maestro-sdk/ios/Maestro SDK/Maestro SDK.xcodeproj/project.pbxproj
maestro-sdk/ios/Maestro SDK/Maestro SDK/MaestroMockServerSdk.swift
maestro-sdk/ios/Maestro SDK/Maestro SDK/MaestroSDK.swift
maestro-sdk/ios/Maestro SDK/Maestro SDK/Maestro_SDK.h
maestro-sdk/ios/Sample/Sample.xcodeproj/project.pbxproj
maestro-sdk/ios/Sample/Sample.xcodeproj/project.xcworkspace/contents.xcworkspacedata
maestro-sdk/ios/Sample/Sample.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
maestro-sdk/ios/Sample/Sample/AppDelegate.swift
maestro-sdk/ios/Sample/Sample/Assets.xcassets/AccentColor.colorset/Contents.json
maestro-sdk/ios/Sample/Sample/Assets.xcassets/AppIcon.appiconset/Contents.json
maestro-sdk/ios/Sample/Sample/Assets.xcassets/Contents.json
maestro-sdk/ios/Sample/Sample/Base.lproj/LaunchScreen.storyboard
maestro-sdk/ios/Sample/Sample/Base.lproj/Main.storyboard
maestro-sdk/ios/Sample/Sample/Info.plist
maestro-sdk/ios/Sample/Sample/SceneDelegate.swift
maestro-sdk/ios/Sample/Sample/ViewController.swift

A basic setup for iOS SDK. 
Publishing scripts and configuration remains to be finalized (going to be done in a different PR)

Feature: iOS SDK

---

maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/resources/screenrecord.sh

Use Simctl instead of IDB to record video:
https://user-images.githubusercontent.com/915211/226653083-ac84766b-7602-419c-8141-33f335203a3a.mp4
See video above

Use Simctl to record video

---

maestro-cli/src/main/java/maestro/cli/runner/CommandState.kt
maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/AnsiResultView.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/UiState.kt
maestro-client/src/main/java/maestro/js/JsConsole.kt
maestro-client/src/main/java/maestro/js/JsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/092_log_messages.yaml
maestro-test/src/test/resources/092_script.js

Added support for `console.log()` method that will attach a message to a command it was executed in

Feature: support console.log

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-client/src/main/java/maestro/debuglog/IOSDriverLogger.kt

Pass the base class to log on to IOSDriverLogger() so that it appears in log lines.

Support custom origin class for IOSDriverLogger

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt

No functional change. Deduplicate the logic for creating an Maestro instance for iOS.

Deduplicate createIOS() logic

---

maestro-studio/web/src/commandExample.ts

Tweak: use consistent quote style in Studio

---

maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt

Reverts mobile-dev-inc/maestro#955

Revert "Restart iOS simulator after permissions reset"

---

maestro-client/src/main/java/maestro/Driver.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-client/src/main/java/maestro/drivers/WebDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/Simctl.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlLaunchApp.kt
maestro-test/src/main/kotlin/maestro/test/drivers/FakeDriver.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/095_launch_arguments.yaml

Android launch arguments are coming soon in another PR

Feature: iOS launch arguments

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt

Proceed only when keyboard is shown
Maestro flow tester
Hidekeyboard clicks even if keyboard is not shown

Don't proceed if keyboard is already hidden

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Text was resolved with help of three text, accessibility text and hint text which is not accounted for copied text in this release

Resolves text properly for copiedText

---

maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/idb/IdbIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

Remove unused pressKey and pressButton implementations

Remove unused pressKey and pressButton implementations

---

maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

Fixes an issue where maestro logs warnings in the form:
`WARNING: A connection to http://localhost:1234/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient`
Tested on staging

Close the http request body after usage

---

RELEASING.md

Updates CONTRIBUTING with deprecated notice

Added deprecated notice for releasing process

---

maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt

Also retry polling the API on 502 Bad Gateway error.

Retry polling api on 502 error

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt

Currently, maestro retries when the server returns a status code above 500. A socket error is not retried.
This PR enables retries on socket errors as well as status codes.
Tested locally by disabling network, running maestro cloud, then enabling network:
```
Uploading Flow(s)...
Upload failed due to socket exception, retrying...
Upload failed due to socket exception, retrying...
Upload failed due to socket exception, retrying...
████████████████████
Visit the web console for more details about the upload: https://console.mobile.dev/uploads/519086d6-3cc7-4898-9bf7-62ca40fc3dc4?teamId=1c1291f2-578f-46bc-8ecc-f61477b1fefa&appId=3e55c3f6-32cc-42f1-bcae-9564ab4b2f55
Waiting for analyses to complete...
[Passed] ios-advanced-flow
```
Uploads that fail due to an intermittent network issue would …

Retry upload on socket exception

---

maestro-client/src/main/java/maestro/js/GraalJsEngine.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Allowing to inject OKHttpClient

chore: Allow OKHttpClient injectable to Orchestra

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt

Path was previously resolved incorrectly by using the main flow path

[fix] correct path resolution for subflows onStart/Complete hooks files

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt

Add support for environments for maestro cloud

Support environments for maestro cloud

---

maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt

Reverts mobile-dev-inc/maestro#1239

Revert "feat: add a more generic retry interceptor to XCTestDriverClient"

---

maestro-studio/web/package-lock.json
maestro-studio/web/package.json
maestro-studio/web/src/components/commands/CommandRow.tsx
maestro-studio/web/src/components/commands/ReplView.tsx
maestro-studio/web/src/components/design-system/input.tsx
maestro-studio/web/src/components/device-and-device-elements/ElementsPanel.tsx
maestro-studio/web/src/components/device-and-device-elements/InteractableDevice.tsx
maestro-studio/web/src/helpers/commandExample.ts

Sidebar resize

---

maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

Close the permissions response

Close permissions response for XCTestDriver

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-cli/src/main/java/maestro/cli/util/ScreenReporter.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt
maestro-utils/src/main/kotlin/DepthTracker.kt

Add insights at shutdown hook for the max depth on iOS screens

Add insights from the max depth on the screens

---

maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-studio/server/build.gradle
maestro-studio/server/src/main/java/maestro/studio/InsightService.kt
maestro-studio/server/src/main/java/maestro/studio/MaestroStudio.kt
maestro-studio/web/src/api/api.ts
maestro-studio/web/src/api/mocks.ts
maestro-studio/web/src/components/common/Header.tsx
maestro-studio/web/src/helpers/models.ts
maestro-utils/src/main/kotlin/Insight.kt

1. Adds `InsightsService` api
2. Checks for 3 seconds for insights and responds with either empty string or valid insight

Adds an API to raise insights on studio

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/CommandState.kt
maestro-cli/src/main/java/maestro/cli/runner/MaestroCommandRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/AnsiResultView.kt
maestro-cli/src/main/java/maestro/cli/runner/resultview/PlainTextResultView.kt
maestro-cli/src/main/java/maestro/cli/view/ViewUtils.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-studio/server/build.gradle
maestro-studio/server/src/main/java/maestro/studio/InsightService.kt
maestro-studio/server/src/main/java/maestro/studio/MaestroStudio.kt
maestro-studio/web/src/api/api.ts
maestro-studio/web/src/api/mocks.ts
maestro-studio/web/src/components/common/Header.tsx
maestro-studio/web/src/helpers/models.ts
maestro-utils/src/main/kotlin/Insight.kt
maestro-utils/src/main/kotlin/Strings.kt

Raise insights when the view hierarchy of screen is too deep
1. Raise the insight when it start taking lot of time 
2. Raise insight on migration of new architecture and the current obtained depth

[MOB 2206] Raising insights on view hierarchy

---

maestro-studio/web/src/components/common/Header.tsx

- Some banner styles fixes like padding and font size
- Added dark theme style to banner

updated banner style & fixed banner style on dark theme

---

maestro-studio/web/src/components/device-and-device-elements/AnnotatedScreenshot.tsx

Increase the opacity of pink lines used to highlight the device elements to make them more visible.

Studio: Increase visibility for pink highlights of Elements in Device

---

maestro-studio/web/src/components/device-and-device-elements/ActionModal.tsx

Added back a visible play button with the commands.

Studio: Added play button with commands

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios-driver/src/main/kotlin/xcuitest/XCTestDriverClient.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-utils/src/main/kotlin/Insight.kt

1. Removed unused subtree api
2. Adds installation for studio command to avoid logging on terminal
3. Avoid duplication of insight on CLI
4. change messaging a bit
Locally with different apps

Bug fixes for maestro CLI

---

maestro-studio/server/src/main/java/maestro/studio/AuthService.kt
maestro-studio/server/src/main/java/maestro/studio/DeviceScreenService.kt
maestro-studio/server/src/main/java/maestro/studio/MaestroStudio.kt

Added Studio API endpoints for retrieving the CLI auth-token and returning the last-view-hierarchy retrieved

Add /api/auth-token and /api/last-view-hierarchy endpoints

---

maestro-studio/server/src/main/java/maestro/studio/DeviceScreenService.kt
maestro-studio/web/src/api/api.ts
maestro-studio/web/src/api/mocks.ts
maestro-studio/web/src/pages/InteractPage.tsx

Use server-sent events instead of polling for device-screen endpoint

Migrate device-screen endpoint to SSE

---

maestro-studio/server/src/main/java/maestro/studio/AuthService.kt

Add endpoints:
* `/api/auth` - GET
* `/api/auth/openai-token` - POST/DELETE

Add endpoints for user OpenAI token

---

maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt
maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

Decouples boot simulator out of launch function (change needed for improving inputText stability on cloud)

decouple simctl boot and launch

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt

Fixes https://github.com/mobile-dev-inc/maestro/issues/1448

fix: can use `_` in timeout for extendedWaitUntil

---

maestro-studio/web/src/components/commands/CommandCreator.tsx

initial paste with enter

---

maestro-ios-driver/src/main/kotlin/util/XCRunnerCLIUtils.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt
maestro-utils/src/main/kotlin/MaestroTimer.kt

- Improved the ensureOpen function to consider both the app being alive and the /status check.

feat: improve retry mechanism to ensure openness of XCUITest Server

---

maestro-client/src/main/java/maestro/KeyCode.kt
maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt
maestro-client/src/main/java/maestro/drivers/IOSDriver.kt
maestro-ios/src/main/java/ios/IOSDevice.kt
maestro-ios/src/main/java/ios/LocalIOSDevice.kt
maestro-ios/src/main/java/ios/simctl/SimctlIOSDevice.kt
maestro-ios/src/main/java/ios/xctest/XCTestIOSDevice.kt

1. This is done to better propagate iOS installation failures which right now are just masked without getting noticed
2. Fix swipe coordinates by ranging them in 0-screenWidth and 0-screenHeight
3. Adding Escape for android driver

refactor: remove result from install

---

maestro-cli/src/main/java/maestro/cli/update/Updates.kt

Adds an option to disable the update check

add an option to disable the update check

---

maestro-cli/src/main/java/maestro/cli/command/StartDeviceCommand.kt

Add ios 17 to start device command
Run the cli, and validate the output

Add ios 17 to start device command

---

maestro-cli/src/main/java/maestro/cli/util/IOSEnvUtils.kt

urgent hotfix
failing https://github.com/mobile-dev-inc/monorepo/actions/runs/10143074227/job/28044768097

Analytics: fix UnsupportedOperationException: Empty collection can't be reduced

---

maestro-ios-xctest-runner/build-maestro-ios-runner.sh

silly mistake on my side + my lack of testing

fix build-maestro-ios-runner.sh

---

maestro-ios-xctest-runner/build-maestro-ios-runner.sh

This fixes the following warning:
<details><summary>Details</summary>
```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
{ platform:iOS Simulator, id:0E9BF126-D656-4529-B102-32B0FCFE4F66, OS:16.4, name:iPad (10th generation) }
{ platform:iOS Simulator, id:0E9BF126-D656-4529-B102-32B0FCFE4F66, OS:16.4, name:iPad (10th generation) }
{ platform:iOS Simulator, id:AD14878A-8CAA-4A2A-B340-4F790949C2D5, OS:17.5, name:iPad (10th generation) }
{ platform:iOS Simulator, id:AD14878A-8CAA-4A2A-B340-4F790949C2D5, OS:17.5, name:iPad (10th generation) }
{ platform:iOS Simulator, id:E2CF2858-61FC-440A-ABD5-AC7696C1802F, OS:16.4, name:iPad Air …
```

Fix warning showing up when building XCTestRunner

---

maestro-cli/src/main/java/maestro/cli/util/IOSEnvUtils.kt

fix #1870
root cause:
- https://stackoverflow.com/questions/72030988/how-to-enforce-null-safety-annotation-checks-in-kotlin
- https://stackoverflow.com/questions/76183897/inference-on-platform-types-after-calling-a-member-of-the-platform-type

fix NPE when uploading analytics, for sure

---

maestro-cli/build.gradle.kts
maestro-cli/src/main/java/maestro/cli/analytics/Analytics.kt

Root cause: logic error in `Analytics` class
Very very obscure though. Lack of clear logging left us unable to accurately debug user's issues.
aimed at #1856

Fix "socket exception"

---

.github/ISSUE_TEMPLATE/feature_request.yaml

feature request template: spacing improvements

---

maestro-cli/src/main/resources/simplelogger.properties

fyi @amanjeetsingh150 @igorsmotto

Delete simplelogger.properties, we do not use simplelogger

---

.github/workflows/publish-cli.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot.yml

should be done in https://github.com/mobile-dev-inc/maestro/pull/1909 but i forgor

Update GitHub Actions to use Java 11

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/cloud/CloudInteractor.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt

Enable maestro cloud to new infra by mentioning project ID and API keys.
Running evergreen tests with few customers.

feat: enable maestro cloud uploads to new infra

---

maestro-client/src/main/java/maestro/Maestro.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/geo/Traveller.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlSetLocation.kt
maestro-orchestra/src/test/java/maestro/orchestra/MaestroCommandTest.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-orchestra/src/test/resources/YamlCommandReaderTest/026_setLocation_syntaxError.yaml
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/028_env.yaml

This PR is a copy of #1769
I accidentally closed #1769 and the "reopen button" is great now. I'm sorry @prasanta-biswas!

Allow env variables in `setLocation` and `travel` commands

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlFluentCommand.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlScrollUntilVisible.kt
maestro-orchestra/src/test/java/maestro/orchestra/yaml/YamlCommandReaderTest.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt
maestro-test/src/test/resources/117_scroll_until_visible_speed.js
maestro-test/src/test/resources/117_scroll_until_visible_speed.yaml

Fix evaluate script bug
fixes #1788

Fix evaluate script bug

---

maestro-cli/src/main/java/maestro/cli/App.kt

https://picocli.info/autocomplete.html

Add `--generate-completion` command

---

maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/command/UploadCommand.kt
maestro-cli/src/main/java/maestro/cli/runner/TestRunner.kt
maestro-cli/src/main/java/maestro/cli/runner/TestSuiteInteractor.kt
maestro-orchestra-models/src/main/java/maestro/orchestra/util/Env.kt
maestro-orchestra-models/src/test/kotlin/maestro/orchestra/util/EnvTest.kt
maestro-orchestra/src/main/java/maestro/orchestra/yaml/YamlCommandReader.kt
maestro-test/src/test/kotlin/maestro/test/IntegrationTest.kt

Following https://github.com/mobile-dev-inc/maestro/pull/1945#issuecomment-2325129713
- Added unit tests for `Env`
- Reran `gradle test`
Linked #1945

Refactor Env and add unit tests

---

maestro-cli/src/main/java/maestro/cli/runner/resultview/AnsiResultView.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt

https://github.com/user-attachments/assets/73a6116d-ef7f-4359-aa59-cda5304a8172
https://github.com/user-attachments/assets/8cead7a1-11f7-4efb-b405-517b52491874

Fix AnsiResultView status emojis having different length

---

maestro-cli/src/main/java/maestro/cli/util/ChangeLogUtils.kt
maestro-cli/src/test/kotlin/maestro/cli/util/ChangeLogUtilsTest.kt

- Prevent a crash if version is not present in changelog
- Add test to make sure any new version has a changelog section
- Update the preview UI
- Add unit test

Fix changelog crash

---

e2e/run_tests
e2e/workspaces/demo_app/ai.yaml
e2e/workspaces/demo_app/commands_optional_tournee.yaml
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Make sure that it also ends up being in HTML AI report

Display AI warnings as insight when `optional: true`

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

Factored out of #1974 to make that PR smaller in size.

A small refactor to LocalXCTestInstaller

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Found it while working on #1974

Orchestra.buildFilter(): remove unused DeviceInfo parameter

---

maestro-ai/src/main/java/maestro/ai/Prediction.kt

reported by user on Maestro AI slack channel

fix AI commands crashing with JSON serde exception when Anthropic is used

---

maestro-cli/src/main/java/maestro/cli/runner/resultview/AnsiResultView.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

AnsiResultsView: improve how multiline message in Insights looks like

---

maestro-studio/server/src/main/java/maestro/studio/DeviceService.kt

fix landscape mode in Maestro Studio on both Android and iOS

---

maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Optional command now throw command warned exception. This code was missing for handling sub flows which caused a regression on cloud.
Locally and cloud

fix: optional commands in subFlow

---

maestro-ai/src/main/java/maestro/ai/DemoApp.kt
maestro-ai/src/main/java/maestro/ai/openai/Client.kt

Just removed some gpt -4 versions with the specified versions in it

removing gpt deprecated versions

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/model/FlowStatus.kt
maestro-cli/src/main/java/maestro/cli/view/TestSuiteStatusView.kt

Added INSTALLING & PREPARING Status for Flows

fix: added installing and preparing status for uploads

---

maestro-android/src/main/java/dev/mobile/maestro/handlers/LocaleSettingHandler.kt
maestro-android/src/main/java/dev/mobile/maestro/receivers/LocaleSettingReceiver.kt

Fix eof when setting device locale. Exception was not being propagated which probably was keeping connections hanging until socket timeout.
setLocaleWith could potentially throwns an EOFException, and if it does, connection from dadb would hang until timeout

Fix eof for setLocale

---

CHANGELOG.md

Adding the correct version summaries

fix(release): changelog with the correct version info

---

maestro-ai/README.md
maestro-ai/src/main/java/maestro/ai/DemoApp.kt
maestro-ai/src/main/java/maestro/ai/anthropic/Client.kt
maestro-ai/src/main/java/maestro/ai/anthropic/Common.kt
maestro-ai/src/main/java/maestro/ai/anthropic/Request.kt
maestro-ai/src/main/java/maestro/ai/anthropic/Response.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

s/antrophic/anthropic/g
Source: www.anthropic.com

Fix typo in Anthropic

---

e2e/workspaces/demo_app/commands/retry.yaml
e2e/workspaces/demo_app/commands_tour.yaml

- Resequenced the commands e2e tests to be alphabetical
- Added a test for the `retry` commands
- Added explicit TODOs for missing commands
- Workflow passed 🤷‍♂️
- Runs locally

Add e2e test for retry command

---

maestro-cli/src/main/java/maestro/cli/command/PrintHierarchyCommand.kt
maestro-cli/src/main/java/maestro/cli/command/QueryCommand.kt
maestro-cli/src/main/java/maestro/cli/command/RecordCommand.kt
maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt
maestro-cli/src/main/java/maestro/cli/command/TestCommand.kt
maestro-cli/src/main/java/maestro/cli/device/DeviceService.kt

fix: update maestro test to respect --host and --port arguments

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Added logs for scroll until visible debug

added logs to scroll until visible

---

maestro-ai/src/main/java/maestro/ai/DemoApp.kt
maestro-ai/src/main/java/maestro/ai/Prediction.kt
maestro-ai/src/main/java/maestro/ai/cloud/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/report/TestDebugReporter.kt
maestro-client/src/main/java/maestro/Errors.kt
maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

This PR refactors ai commands to leverage the Maestro Cloud endpoint, streamlining text extraction for improved efficiency and maintainability. The local implementation is simplified by offloading this process to the cloud, reducing code complexity while potentially enhancing accuracy and performance.
N/A

refactor(ai): Update extractTextWithAi to use Maestro Cloud endpoint

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

Reverts mobile-dev-inc/Maestro#2288

Revert "feat: start trial option if not started"

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt
maestro-cli/src/main/java/maestro/cli/command/CloudCommand.kt

Reverts mobile-dev-inc/Maestro#2297

Revert "Revert "feat: start trial option if not started""

---

maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

Trying to change the clearKeyChain implementation since the older one gives permissions errors while deletion of keychain directory.

fix: clearKeychain command

---

maestro-cli/src/main/java/maestro/cli/App.kt
maestro-cli/src/main/java/maestro/cli/util/DeviceConfig.kt
maestro-cli/src/main/java/maestro/cli/util/EnvUtils.kt
maestro-cli/src/main/java/maestro/cli/util/WorkspaceUtils.kt
maestro-client/src/main/java/maestro/device/util/AndroidEnvUtils.kt

Fixes a few reported bugs on Windows.
* Fixes the `maestro cloud` command (a widely reported problem)
* Fixes some problems in `maestro start-device` but not quite enough to make it actually work
Tested on Windows 11
#2273 #2281 #2282

Fix a few windows woes

---

maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

Reverts mobile-dev-inc/Maestro#2389

Revert "increasing IOS timeout to avoid errors"

---

maestro-ios-driver/src/main/kotlin/xcuitest/installer/LocalXCTestInstaller.kt

`TMPDIR` isn't always defined. This uses Java's provided temp dir method instead.

use os-provided temp dir instead of bash variable

---

maestro-orchestra/src/main/java/maestro/orchestra/Orchestra.kt

Adding logs for AI commands by updating its metadata

adding metadata logs to AI commands

---

maestro-ios-driver/src/main/kotlin/util/IOSDevice.kt

These properties can be nullable.
Locally

fix: transport type can be null

---

maestro-ios-driver/src/main/kotlin/util/LocalSimulatorUtils.kt

Reverts mobile-dev-inc/Maestro#2540

Revert "using a better error handling"

---

maestro-cli/src/main/java/maestro/cli/session/MaestroSessionManager.kt
maestro-client/src/main/java/maestro/Maestro.kt
maestro-client/src/main/java/maestro/drivers/CdpWebDriver.kt
maestro-web/build.gradle.kts
maestro-web/src/main/kotlin/maestro/web/cdp/CdpClient.kt

A driver that uses a combination of Selenium and CDP to interact with the browser. Though Selenium is not completely out of the picture yet, the new implementation is already significantly faster. Most importantly, it doesn't steal the focus allowing it to run alongside Maestro Studio.

CDP Web Driver

---

maestro-cli/src/main/java/maestro/cli/command/StudioCommand.kt

Show download link when running `maestro studio`

Download studio link

---

maestro-cli/build.gradle.kts

This PR modifies both the bash (for unix* systems) and bat (for Windows) so that it detects the minimum version (currently 17) of java before executing the main maestro-cli java process.
The easiest way to test this is firstly clean the maestro build
```sh
./gradlew clean
```
Then lets create a package using jreleaser (make sure you are running java version 17 for this step)
```sh
export JRELEASER_GITHUB_TOKEN=not used
./gradlew :maestro-cli:jreleaserPackage --no-daemon --no-parallel
```
This will create the distributions at `maestro-cli/build/distributions` so lets unzip them and try out the start script
```sh
<@Maestro>cd maestro-cli/build/distributions/
<@Maestro/m/b/distributions>unzip maestro.zip 
Archive:  maestro.zip
creating: maestro
creating: maestro/lib
inflating: …
```

feat: Detect minimum JVM version

---

maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt

Making abrupt close variable from android driver public so that it can be used by consumers.

chore: make abruptClose public

---

.idea/.gitignore

Annoying cruft from Microsoft's plugin that denotes some local state.

Add Copilot plugin files to .idea gitignore

---

maestro-cli/src/main/java/maestro/cli/api/ApiClient.kt

Removes baseUrl debug logging from console output

Remove debug logging

---

RELEASING.md

fix: Fix broken publish cli link
